package ec.com.rgt.sair.hbm;

// Generated 08-jul-2013 0:41:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GruposRolesId generated by hbmjava
 */
@SuppressWarnings("serial")
public class GruposRolesId implements java.io.Serializable {

	private BigDecimal idGrupo;
	private BigDecimal idRol;

	public GruposRolesId() {
	}

	public GruposRolesId(BigDecimal idGrupo, BigDecimal idRol) {
		this.idGrupo = idGrupo;
		this.idRol = idRol;
	}

	public BigDecimal getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(BigDecimal idGrupo) {
		this.idGrupo = idGrupo;
	}

	public BigDecimal getIdRol() {
		return this.idRol;
	}

	public void setIdRol(BigDecimal idRol) {
		this.idRol = idRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GruposRolesId))
			return false;
		GruposRolesId castOther = (GruposRolesId) other;

		return ((this.getIdGrupo() == castOther.getIdGrupo()) || (this
				.getIdGrupo() != null && castOther.getIdGrupo() != null && this
				.getIdGrupo().equals(castOther.getIdGrupo())))
				&& ((this.getIdRol() == castOther.getIdRol()) || (this
						.getIdRol() != null && castOther.getIdRol() != null && this
						.getIdRol().equals(castOther.getIdRol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdGrupo() == null ? 0 : this.getIdGrupo().hashCode());
		result = 37 * result
				+ (getIdRol() == null ? 0 : this.getIdRol().hashCode());
		return result;
	}

}
