package ec.com.rgt.sair.hbm;

// Generated 08-jul-2013 0:41:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GruposMenuId generated by hbmjava
 */
@SuppressWarnings("serial")
public class GruposMenuId implements java.io.Serializable {

	private BigDecimal idGrupo;
	private BigDecimal idMenu;

	public GruposMenuId() {
	}

	public GruposMenuId(BigDecimal idGrupo, BigDecimal idMenu) {
		this.idGrupo = idGrupo;
		this.idMenu = idMenu;
	}

	public BigDecimal getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(BigDecimal idGrupo) {
		this.idGrupo = idGrupo;
	}

	public BigDecimal getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(BigDecimal idMenu) {
		this.idMenu = idMenu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GruposMenuId))
			return false;
		GruposMenuId castOther = (GruposMenuId) other;

		return ((this.getIdGrupo() == castOther.getIdGrupo()) || (this
				.getIdGrupo() != null && castOther.getIdGrupo() != null && this
				.getIdGrupo().equals(castOther.getIdGrupo())))
				&& ((this.getIdMenu() == castOther.getIdMenu()) || (this
						.getIdMenu() != null && castOther.getIdMenu() != null && this
						.getIdMenu().equals(castOther.getIdMenu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdGrupo() == null ? 0 : this.getIdGrupo().hashCode());
		result = 37 * result
				+ (getIdMenu() == null ? 0 : this.getIdMenu().hashCode());
		return result;
	}

}
