package ec.com.rgt.sair.hbm;

// Generated 12-ago-2014 11:50:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GruposAplicacionesId generated by hbmjava
 */
@SuppressWarnings("serial")
public class GruposAplicacionesId implements java.io.Serializable {

	private BigDecimal idGrupo;
	private BigDecimal idAplicacion;

	public GruposAplicacionesId() {
	}

	public GruposAplicacionesId(BigDecimal idGrupo, BigDecimal idAplicacion) {
		this.idGrupo = idGrupo;
		this.idAplicacion = idAplicacion;
	}

	public BigDecimal getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(BigDecimal idGrupo) {
		this.idGrupo = idGrupo;
	}

	public BigDecimal getIdAplicacion() {
		return this.idAplicacion;
	}

	public void setIdAplicacion(BigDecimal idAplicacion) {
		this.idAplicacion = idAplicacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GruposAplicacionesId))
			return false;
		GruposAplicacionesId castOther = (GruposAplicacionesId) other;

		return ((this.getIdGrupo() == castOther.getIdGrupo()) || (this
				.getIdGrupo() != null && castOther.getIdGrupo() != null && this
				.getIdGrupo().equals(castOther.getIdGrupo())))
				&& ((this.getIdAplicacion() == castOther.getIdAplicacion()) || (this
						.getIdAplicacion() != null
						&& castOther.getIdAplicacion() != null && this
						.getIdAplicacion().equals(castOther.getIdAplicacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdGrupo() == null ? 0 : this.getIdGrupo().hashCode());
		result = 37
				* result
				+ (getIdAplicacion() == null ? 0 : this.getIdAplicacion()
						.hashCode());
		return result;
	}

}
