package ec.com.rgt.sair.hbm;

//Generated 11-feb-2019 14:27:54 by Hibernate Tools 3.4.0.CR1

/**
* MasivoCasosObs generated by hbmjava
*/

public class MasivoCasosObs {
	private String idObservacion;
	private String idArea;
	private String idUsuarioAic;
	private String observacion;
	private String idOperador;
	private String idDepartamento;
	private String idSubArea;
	private String idCiudad;	
	private String mesPeriodo;
	private String cuenta;	
	private String telefono;
	private String valor;	
	private String codIncidencia;	
	private String idTipo;
	private String fechaRespAud;	
	private String idComentario;
	private String idTipoFalta;
	private String idDetalleFaltas;
	private String idSecuenciaReservaCodigo;
	private String anio;
	private String idLocalidad;
	private String idRecomendacion;
	private String idSupervisor;
	
	
	public MasivoCasosObs() {
		
	}


	public MasivoCasosObs(String idObservacion, String idArea, String idUsuarioAic, String observacion,
			String idOperador, String idDepartamento, String idSubArea, String idCiudad, String mesPeriodo,
			String cuenta, String telefono, String valor, String codIncidencia, String idTipo, String fechaRespAud,
			String idComentario, String idTipoFalta, String idDetalleFaltas, String idSecuenciaReservaCodigo,
			String anio, String idLocalidad, String idRecomendacion, String idSupervisor) {
		this.idObservacion = idObservacion;
		this.idArea = idArea;
		this.idUsuarioAic = idUsuarioAic;
		this.observacion = observacion;
		this.idOperador = idOperador;
		this.idDepartamento = idDepartamento;
		this.idSubArea = idSubArea;
		this.idCiudad = idCiudad;
		this.mesPeriodo = mesPeriodo;
		this.cuenta = cuenta;
		this.telefono = telefono;
		this.valor = valor;
		this.codIncidencia = codIncidencia;
		this.idTipo = idTipo;
		this.fechaRespAud = fechaRespAud;
		this.idComentario = idComentario;
		this.idTipoFalta = idTipoFalta;
		this.idDetalleFaltas = idDetalleFaltas;
		this.idSecuenciaReservaCodigo = idSecuenciaReservaCodigo;
		this.anio = anio;
		this.idLocalidad = idLocalidad;
		this.idRecomendacion = idRecomendacion;
		this.idSupervisor = idSupervisor;
	}


	public String getIdObservacion() {
		return idObservacion;
	}


	public void setIdObservacion(String idObservacion) {
		this.idObservacion = idObservacion;
	}


	public String getIdArea() {
		return idArea;
	}


	public void setIdArea(String idArea) {
		this.idArea = idArea;
	}


	public String getIdUsuarioAic() {
		return idUsuarioAic;
	}


	public void setIdUsuarioAic(String idUsuarioAic) {
		this.idUsuarioAic = idUsuarioAic;
	}


	public String getObservacion() {
		return observacion;
	}


	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}


	public String getIdOperador() {
		return idOperador;
	}


	public void setIdOperador(String idOperador) {
		this.idOperador = idOperador;
	}


	public String getIdDepartamento() {
		return idDepartamento;
	}


	public void setIdDepartamento(String idDepartamento) {
		this.idDepartamento = idDepartamento;
	}


	public String getIdSubArea() {
		return idSubArea;
	}


	public void setIdSubArea(String idSubArea) {
		this.idSubArea = idSubArea;
	}


	public String getIdCiudad() {
		return idCiudad;
	}


	public void setIdCiudad(String idCiudad) {
		this.idCiudad = idCiudad;
	}


	public String getMesPeriodo() {
		return mesPeriodo;
	}


	public void setMesPeriodo(String mesPeriodo) {
		this.mesPeriodo = mesPeriodo;
	}


	public String getCuenta() {
		return cuenta;
	}


	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}


	public String getTelefono() {
		return telefono;
	}


	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}


	public String getValor() {
		return valor;
	}


	public void setValor(String valor) {
		this.valor = valor;
	}


	public String getCodIncidencia() {
		return codIncidencia;
	}


	public void setCodIncidencia(String codIncidencia) {
		this.codIncidencia = codIncidencia;
	}


	public String getIdTipo() {
		return idTipo;
	}


	public void setIdTipo(String idTipo) {
		this.idTipo = idTipo;
	}


	public String getFechaRespAud() {
		return fechaRespAud;
	}


	public void setFechaRespAud(String fechaRespAud) {
		this.fechaRespAud = fechaRespAud;
	}


	public String getIdComentario() {
		return idComentario;
	}


	public void setIdComentario(String idComentario) {
		this.idComentario = idComentario;
	}


	public String getIdTipoFalta() {
		return idTipoFalta;
	}


	public void setIdTipoFalta(String idTipoFalta) {
		this.idTipoFalta = idTipoFalta;
	}


	public String getIdDetalleFaltas() {
		return idDetalleFaltas;
	}


	public void setIdDetalleFaltas(String idDetalleFaltas) {
		this.idDetalleFaltas = idDetalleFaltas;
	}


	public String getIdSecuenciaReservaCodigo() {
		return idSecuenciaReservaCodigo;
	}


	public void setIdSecuenciaReservaCodigo(String idSecuenciaReservaCodigo) {
		this.idSecuenciaReservaCodigo = idSecuenciaReservaCodigo;
	}


	public String getAnio() {
		return anio;
	}


	public void setAnio(String anio) {
		this.anio = anio;
	}


	public String getIdLocalidad() {
		return idLocalidad;
	}


	public void setIdLocalidad(String idLocalidad) {
		this.idLocalidad = idLocalidad;
	}


	public String getIdRecomendacion() {
		return idRecomendacion;
	}


	public void setIdRecomendacion(String idRecomendacion) {
		this.idRecomendacion = idRecomendacion;
	}


	public String getIdSupervisor() {
		return idSupervisor;
	}


	public void setIdSupervisor(String idSupervisor) {
		this.idSupervisor = idSupervisor;
	}
	
	
	

}
