package ec.com.rgt.sair.hbm;

// Generated 08-jul-2013 0:41:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Permisos generated by hbmjava
 */
@SuppressWarnings("serial")
public class Permisos implements java.io.Serializable {

	private BigDecimal idPermiso;
	private String nombrePermiso;
	private String usuarioIngreso;
	private Date fechaInicio;
	private String usuarioModificacion;
	private Date fechaBaja;
	private String estado;

	public Permisos() {
	}

	public Permisos(BigDecimal idPermiso, String nombrePermiso,
			String usuarioIngreso, Date fechaInicio, String estado) {
		this.idPermiso = idPermiso;
		this.nombrePermiso = nombrePermiso;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public Permisos(BigDecimal idPermiso, String nombrePermiso,
			String usuarioIngreso, Date fechaInicio,
			String usuarioModificacion, Date fechaBaja, String estado) {
		this.idPermiso = idPermiso;
		this.nombrePermiso = nombrePermiso;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaInicio = fechaInicio;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaBaja = fechaBaja;
		this.estado = estado;
	}

	public BigDecimal getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(BigDecimal idPermiso) {
		this.idPermiso = idPermiso;
	}

	public String getNombrePermiso() {
		return this.nombrePermiso;
	}

	public void setNombrePermiso(String nombrePermiso) {
		this.nombrePermiso = nombrePermiso;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
