package ec.com.rgt.sair.hbm;

// Generated 21/04/2014 11:54:37 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RecomendacionHistorica generated by hbmjava
 */
@SuppressWarnings("serial")
public class RecomendacionHistorica implements java.io.Serializable {

	private BigDecimal idRecomendacionHistorica;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairEstadoComplementario sairEstadoComplementario;
	private SairDocConclusionDocumento sairDocConclusionDocumento;
	private SairArea sairArea;
	private SairAreasAdam sairAreasAdam;
	private BigDecimal idRecomendacion;
	private String personaEncargada;
	private String gerenteEncargado;
	private String descripcion;
	private BigDecimal evaluacion;
	private Date fechaAtencionTotal;
	private Date fechaCompromiso;
	private Date fechaRespuesta;
	private Date fechaDeBaja;
	private Date fechaDeEmision;
	private String dependeProveedor;
	private String codigo;
	private BigDecimal numero;
	private Date fechaIngreso;
	private BigDecimal ano;
	private String atendida;
	private String areaEvaluada;
	private String estado;
	private String conclusion;
	private String comentario;
	private Date fechaActualizacion;
	private String errorOperativo;

	public RecomendacionHistorica() {
	}

	public RecomendacionHistorica(BigDecimal idRecomendacionHistorica) {
		this.idRecomendacionHistorica = idRecomendacionHistorica;
	}

	public RecomendacionHistorica(BigDecimal idRecomendacionHistorica,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairEstadoComplementario sairEstadoComplementario,
			SairDocConclusionDocumento sairDocConclusionDocumento,
			SairArea sairArea, SairAreasAdam sairAreasAdam,
			BigDecimal idRecomendacion, String personaEncargada,
			String gerenteEncargado, String descripcion, BigDecimal evaluacion,
			Date fechaAtencionTotal, Date fechaCompromiso, Date fechaRespuesta,
			Date fechaDeBaja, String dependeProveedor, String codigo,
			BigDecimal numero, Date fechaIngreso, BigDecimal ano,
			String atendida, String areaEvaluada, String estado,
			String conclusion, String comentario, Date fechaActualizacion, Date fechaDeEmision,
			String errorOperativo) {
		this.idRecomendacionHistorica = idRecomendacionHistorica;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairEstadoComplementario = sairEstadoComplementario;
		this.sairDocConclusionDocumento = sairDocConclusionDocumento;
		this.sairArea = sairArea;
		this.sairAreasAdam = sairAreasAdam;
		this.idRecomendacion = idRecomendacion;
		this.personaEncargada = personaEncargada;
		this.gerenteEncargado = gerenteEncargado;
		this.descripcion = descripcion;
		this.evaluacion = evaluacion;
		this.fechaAtencionTotal = fechaAtencionTotal;
		this.fechaCompromiso = fechaCompromiso;
		this.fechaRespuesta = fechaRespuesta;
		this.fechaDeBaja = fechaDeBaja;
		this.dependeProveedor = dependeProveedor;
		this.codigo = codigo;
		this.numero = numero;
		this.fechaIngreso = fechaIngreso;
		this.ano = ano;
		this.atendida = atendida;
		this.areaEvaluada = areaEvaluada;
		this.estado = estado;
		this.conclusion = conclusion;
		this.comentario = comentario;
		this.fechaActualizacion = fechaActualizacion;
		this.fechaDeEmision = fechaDeEmision;
		this.errorOperativo=errorOperativo;
		
	}

	public Date getFechaDeEmision() {
		return fechaDeEmision;
	}

	public void setFechaDeEmision(Date fechaDeEmision) {
		this.fechaDeEmision = fechaDeEmision;
	}

	public BigDecimal getIdRecomendacionHistorica() {
		return this.idRecomendacionHistorica;
	}

	public void setIdRecomendacionHistorica(BigDecimal idRecomendacionHistorica) {
		this.idRecomendacionHistorica = idRecomendacionHistorica;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairEstadoComplementario getSairEstadoComplementario() {
		return this.sairEstadoComplementario;
	}

	public void setSairEstadoComplementario(
			SairEstadoComplementario sairEstadoComplementario) {
		this.sairEstadoComplementario = sairEstadoComplementario;
	}

	public SairDocConclusionDocumento getSairDocConclusionDocumento() {
		return this.sairDocConclusionDocumento;
	}

	public void setSairDocConclusionDocumento(
			SairDocConclusionDocumento sairDocConclusionDocumento) {
		this.sairDocConclusionDocumento = sairDocConclusionDocumento;
	}

	public SairArea getSairArea() {
		return this.sairArea;
	}

	public void setSairArea(SairArea sairArea) {
		this.sairArea = sairArea;
	}

	public SairAreasAdam getSairAreasAdam() {
		return this.sairAreasAdam;
	}

	public void setSairAreasAdam(SairAreasAdam sairAreasAdam) {
		this.sairAreasAdam = sairAreasAdam;
	}

	public BigDecimal getIdRecomendacion() {
		return this.idRecomendacion;
	}

	public void setIdRecomendacion(BigDecimal idRecomendacion) {
		this.idRecomendacion = idRecomendacion;
	}

	public String getPersonaEncargada() {
		return this.personaEncargada;
	}

	public void setPersonaEncargada(String personaEncargada) {
		this.personaEncargada = personaEncargada;
	}

	public String getGerenteEncargado() {
		return this.gerenteEncargado;
	}

	public void setGerenteEncargado(String gerenteEncargado) {
		this.gerenteEncargado = gerenteEncargado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(BigDecimal evaluacion) {
		this.evaluacion = evaluacion;
	}

	public Date getFechaAtencionTotal() {
		return this.fechaAtencionTotal;
	}

	public void setFechaAtencionTotal(Date fechaAtencionTotal) {
		this.fechaAtencionTotal = fechaAtencionTotal;
	}

	public Date getFechaCompromiso() {
		return this.fechaCompromiso;
	}

	public void setFechaCompromiso(Date fechaCompromiso) {
		this.fechaCompromiso = fechaCompromiso;
	}

	public Date getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Date fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	public Date getFechaDeBaja() {
		return this.fechaDeBaja;
	}

	public void setFechaDeBaja(Date fechaDeBaja) {
		this.fechaDeBaja = fechaDeBaja;
	}

	public String getDependeProveedor() {
		return this.dependeProveedor;
	}

	public void setDependeProveedor(String dependeProveedor) {
		this.dependeProveedor = dependeProveedor;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public BigDecimal getNumero() {
		return this.numero;
	}

	public void setNumero(BigDecimal numero) {
		this.numero = numero;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public BigDecimal getAno() {
		return this.ano;
	}

	public void setAno(BigDecimal ano) {
		this.ano = ano;
	}

	public String getAtendida() {
		return this.atendida;
	}

	public void setAtendida(String atendida) {
		this.atendida = atendida;
	}

	public String getAreaEvaluada() {
		return this.areaEvaluada;
	}

	public void setAreaEvaluada(String areaEvaluada) {
		this.areaEvaluada = areaEvaluada;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getConclusion() {
		return this.conclusion;
	}

	public void setConclusion(String conclusion) {
		this.conclusion = conclusion;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public String getErrorOperativo() {
		return this.errorOperativo;
	}

	public void setErrorOperativo(String errorOperativo) {
		this.errorOperativo = errorOperativo;
	}
}
