package ec.com.rgt.sair.hbm;

// Generated 08-jul-2013 0:41:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RolesPermisosId generated by hbmjava
 */
@SuppressWarnings("serial")
public class RolesPermisosId implements java.io.Serializable {

	private BigDecimal idRol;
	private BigDecimal idPermiso;

	public RolesPermisosId() {
	}

	public RolesPermisosId(BigDecimal idRol, BigDecimal idPermiso) {
		this.idRol = idRol;
		this.idPermiso = idPermiso;
	}

	public BigDecimal getIdRol() {
		return this.idRol;
	}

	public void setIdRol(BigDecimal idRol) {
		this.idRol = idRol;
	}

	public BigDecimal getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(BigDecimal idPermiso) {
		this.idPermiso = idPermiso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolesPermisosId))
			return false;
		RolesPermisosId castOther = (RolesPermisosId) other;

		return ((this.getIdRol() == castOther.getIdRol()) || (this.getIdRol() != null
				&& castOther.getIdRol() != null && this.getIdRol().equals(
				castOther.getIdRol())))
				&& ((this.getIdPermiso() == castOther.getIdPermiso()) || (this
						.getIdPermiso() != null
						&& castOther.getIdPermiso() != null && this
						.getIdPermiso().equals(castOther.getIdPermiso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdRol() == null ? 0 : this.getIdRol().hashCode());
		result = 37 * result
				+ (getIdPermiso() == null ? 0 : this.getIdPermiso().hashCode());
		return result;
	}

}
