package ec.com.rgt.sair.hbm;

// Generated 01-oct-2013 10:39:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Rsa generated by hbmjava
 */
@SuppressWarnings("serial")
public class Rsa implements java.io.Serializable {

	private BigDecimal idRsa;
	private BigDecimal valorP;
	private BigDecimal valorQ;
	private BigDecimal valorN;
	private BigDecimal publicoE;
	private BigDecimal privadoD;
	private BigDecimal totient;
	private String ip;

	public Rsa() {
	}

	public Rsa(BigDecimal idRsa) {
		this.idRsa = idRsa;
	}

	public Rsa(BigDecimal idRsa, BigDecimal valorP, BigDecimal valorQ,
			BigDecimal valorN, BigDecimal publicoE, BigDecimal privadoD,
			BigDecimal totient, String ip) {
		this.idRsa = idRsa;
		this.valorP = valorP;
		this.valorQ = valorQ;
		this.valorN = valorN;
		this.publicoE = publicoE;
		this.privadoD = privadoD;
		this.totient = totient;
		this.ip = ip;
	}

	public BigDecimal getIdRsa() {
		return this.idRsa;
	}

	public void setIdRsa(BigDecimal idRsa) {
		this.idRsa = idRsa;
	}

	public BigDecimal getValorP() {
		return this.valorP;
	}

	public void setValorP(BigDecimal valorP) {
		this.valorP = valorP;
	}

	public BigDecimal getValorQ() {
		return this.valorQ;
	}

	public void setValorQ(BigDecimal valorQ) {
		this.valorQ = valorQ;
	}

	public BigDecimal getValorN() {
		return this.valorN;
	}

	public void setValorN(BigDecimal valorN) {
		this.valorN = valorN;
	}

	public BigDecimal getPublicoE() {
		return this.publicoE;
	}

	public void setPublicoE(BigDecimal publicoE) {
		this.publicoE = publicoE;
	}

	public BigDecimal getPrivadoD() {
		return this.privadoD;
	}

	public void setPrivadoD(BigDecimal privadoD) {
		this.privadoD = privadoD;
	}

	public BigDecimal getTotient() {
		return this.totient;
	}

	public void setTotient(BigDecimal totient) {
		this.totient = totient;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

}
