package ec.com.rgt.sair.hbm;

// Generated 09-abr-2015 16:20:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairCalEventos generated by hbmjava
 */
public class SairCalEventos implements java.io.Serializable {

	private BigDecimal idEvento;
	private SairCalTipoEvento sairCalTipoEvento;
	private BigDecimal idObjeto;
	private Date fechaInicio;
	private Date fechaFin;
	private String titulo;
	private String contenido;
	private BigDecimal bloqueado;

	public SairCalEventos() {
	}

	public SairCalEventos(BigDecimal idEvento,
			SairCalTipoEvento sairCalTipoEvento, String titulo,
			BigDecimal bloqueado) {
		this.idEvento = idEvento;
		this.sairCalTipoEvento = sairCalTipoEvento;
		this.titulo = titulo;
		this.bloqueado = bloqueado;
	}

	public SairCalEventos(BigDecimal idEvento,
			SairCalTipoEvento sairCalTipoEvento, BigDecimal idObjeto,
			Date fechaInicio, Date fechaFin, String titulo, String contenido,
			BigDecimal bloqueado) {
		this.idEvento = idEvento;
		this.sairCalTipoEvento = sairCalTipoEvento;
		this.idObjeto = idObjeto;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.titulo = titulo;
		this.contenido = contenido;
		this.bloqueado = bloqueado;
	}

	public BigDecimal getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(BigDecimal idEvento) {
		this.idEvento = idEvento;
	}

	public SairCalTipoEvento getSairCalTipoEvento() {
		return this.sairCalTipoEvento;
	}

	public void setSairCalTipoEvento(SairCalTipoEvento sairCalTipoEvento) {
		this.sairCalTipoEvento = sairCalTipoEvento;
	}

	public BigDecimal getIdObjeto() {
		return this.idObjeto;
	}

	public void setIdObjeto(BigDecimal idObjeto) {
		this.idObjeto = idObjeto;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public BigDecimal getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(BigDecimal bloqueado) {
		this.bloqueado = bloqueado;
	}

}
