package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairTiempoAtencionDocumento generated by hbmjava
 */
public class SairTiempoAtencionDocumento implements java.io.Serializable {

	private BigDecimal idTiempoAtencion;
	private SairDocTipoInforme sairDocTipoInforme;
	private SairDocTipoDocumento sairDocTipoDocumento;
	private String usuarioIngreso;
	private Date fechaIngreso;
	private Date fechaActualizacion;
	private BigDecimal dias;

	public SairTiempoAtencionDocumento() {
	}

	public SairTiempoAtencionDocumento(BigDecimal idTiempoAtencion,
			SairDocTipoInforme sairDocTipoInforme,
			SairDocTipoDocumento sairDocTipoDocumento, String usuarioIngreso,
			Date fechaIngreso, Date fechaActualizacion, BigDecimal dias) {
		this.idTiempoAtencion = idTiempoAtencion;
		this.sairDocTipoInforme = sairDocTipoInforme;
		this.sairDocTipoDocumento = sairDocTipoDocumento;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaIngreso = fechaIngreso;
		this.fechaActualizacion = fechaActualizacion;
		this.dias = dias;
	}

	public BigDecimal getIdTiempoAtencion() {
		return this.idTiempoAtencion;
	}

	public void setIdTiempoAtencion(BigDecimal idTiempoAtencion) {
		this.idTiempoAtencion = idTiempoAtencion;
	}

	public SairDocTipoInforme getSairDocTipoInforme() {
		return this.sairDocTipoInforme;
	}

	public void setSairDocTipoInforme(SairDocTipoInforme sairDocTipoInforme) {
		this.sairDocTipoInforme = sairDocTipoInforme;
	}

	public SairDocTipoDocumento getSairDocTipoDocumento() {
		return this.sairDocTipoDocumento;
	}

	public void setSairDocTipoDocumento(
			SairDocTipoDocumento sairDocTipoDocumento) {
		this.sairDocTipoDocumento = sairDocTipoDocumento;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public BigDecimal getDias() {
		return this.dias;
	}

	public void setDias(BigDecimal dias) {
		this.dias = dias;
	}

}
