package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocRiesgoRc generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocRiesgoRc implements java.io.Serializable {

	private BigDecimal idReisgoRc;
	private SairDocRequerimientoCorrecc sairDocRequerimientoCorrecc;
	private SairDocRiesgoDocumento sairDocRiesgoDocumento;

	public SairDocRiesgoRc() {
	}

	public SairDocRiesgoRc(BigDecimal idReisgoRc,
			SairDocRequerimientoCorrecc sairDocRequerimientoCorrecc,
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.idReisgoRc = idReisgoRc;
		this.sairDocRequerimientoCorrecc = sairDocRequerimientoCorrecc;
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

	public BigDecimal getIdReisgoRc() {
		return this.idReisgoRc;
	}

	public void setIdReisgoRc(BigDecimal idReisgoRc) {
		this.idReisgoRc = idReisgoRc;
	}

	public SairDocRequerimientoCorrecc getSairDocRequerimientoCorrecc() {
		return this.sairDocRequerimientoCorrecc;
	}

	public void setSairDocRequerimientoCorrecc(
			SairDocRequerimientoCorrecc sairDocRequerimientoCorrecc) {
		this.sairDocRequerimientoCorrecc = sairDocRequerimientoCorrecc;
	}

	public SairDocRiesgoDocumento getSairDocRiesgoDocumento() {
		return this.sairDocRiesgoDocumento;
	}

	public void setSairDocRiesgoDocumento(
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

}
