package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairObsComentarioAic generated by hbmjava
 */
public class SairObsComentarioAic implements java.io.Serializable {

	private BigDecimal idComentario;
	private String descripcion;
	private String codigo;
	private String estado;
	

	public SairObsComentarioAic() {
	}

	public SairObsComentarioAic(BigDecimal idComentario, String descripcion) {
		this.idComentario = idComentario;
		this.descripcion = descripcion;
	}

	public SairObsComentarioAic(BigDecimal idComentario, String descripcion,
			String codigo,String estado) {
		this.idComentario = idComentario;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.estado=estado;
	}

	public BigDecimal getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(BigDecimal idComentario) {
		this.idComentario = idComentario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
}
