package ec.com.rgt.sair.hbm;

// Generated 08-sep-2014 9:53:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairRutinaProceso generated by hbmjava
 */
public class SairRutinaProceso implements java.io.Serializable {

	private BigDecimal idRutPro;
	private SairParRutina sairParRutina;
	private SairPoliticaProcedimiento sairPoliticaProcedimiento;

	public SairRutinaProceso() {
	}

	public SairRutinaProceso(BigDecimal idRutPro) {
		this.idRutPro = idRutPro;
	}

	public SairRutinaProceso(BigDecimal idRutPro, SairParRutina sairParRutina,
			SairPoliticaProcedimiento sairPoliticaProcedimiento) {
		this.idRutPro = idRutPro;
		this.sairParRutina = sairParRutina;
		this.sairPoliticaProcedimiento = sairPoliticaProcedimiento;
	}

	public BigDecimal getIdRutPro() {
		return this.idRutPro;
	}

	public void setIdRutPro(BigDecimal idRutPro) {
		this.idRutPro = idRutPro;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}

	public SairPoliticaProcedimiento getSairPoliticaProcedimiento() {
		return this.sairPoliticaProcedimiento;
	}

	public void setSairPoliticaProcedimiento(
			SairPoliticaProcedimiento sairPoliticaProcedimiento) {
		this.sairPoliticaProcedimiento = sairPoliticaProcedimiento;
	}

}
