package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairFrecuencia generated by hbmjava
 */
public class SairFrecuencia implements java.io.Serializable {

	private BigDecimal idFrecuencia;
	private String nombreFrecuencia;
	private String estado;

	public SairFrecuencia() {
	}

	public SairFrecuencia(BigDecimal idFrecuencia) {
		this.idFrecuencia = idFrecuencia;
	}

	public SairFrecuencia(BigDecimal idFrecuencia, String nombreFrecuencia,
			String estado) {
		this.idFrecuencia = idFrecuencia;
		this.nombreFrecuencia = nombreFrecuencia;
		this.estado = estado;

	}

	public BigDecimal getIdFrecuencia() {
		return this.idFrecuencia;
	}

	public void setIdFrecuencia(BigDecimal idFrecuencia) {
		this.idFrecuencia = idFrecuencia;
	}

	public String getNombreFrecuencia() {
		return this.nombreFrecuencia;
	}

	public void setNombreFrecuencia(String nombreFrecuencia) {
		this.nombreFrecuencia = nombreFrecuencia;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
