package ec.com.rgt.sair.hbm;
// Generated 10-nov-2015 9:38:15 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairPantalla generated by hbmjava
 */
public class SairPantalla implements java.io.Serializable {

	private BigDecimal idPantalla,idAplicacion;
	private String nombre,permiso;
	private String src;
	private String estado;
	private Set sairPantallaUsuarios = new HashSet(0);

	public SairPantalla() {
	}

	public SairPantalla(BigDecimal idPantalla, String nombre, String src, String estado,String permiso) {
		this.idPantalla = idPantalla;
		this.nombre = nombre;
		this.src = src;
		this.estado = estado;
		this.permiso = permiso;
	}

	public SairPantalla(BigDecimal idPantalla, String nombre, String src, String estado,String permiso,BigDecimal idAplicacion, Set sairPantallaUsuarios) {
		this.idPantalla = idPantalla;
		this.nombre = nombre;
		this.src = src;
		this.estado = estado;
		this.permiso = permiso;
		this.idAplicacion = idAplicacion;
		this.sairPantallaUsuarios = sairPantallaUsuarios;
	}

	
	public BigDecimal getIdAplicacion() {
		return idAplicacion;
	}

	public void setIdAplicacion(BigDecimal idAplicacion) {
		this.idAplicacion = idAplicacion;
	}

	public String getPermiso() {
		return permiso;
	}

	public void setPermiso(String permiso) {
		this.permiso = permiso;
	}

	public BigDecimal getIdPantalla() {
		return this.idPantalla;
	}

	public void setIdPantalla(BigDecimal idPantalla) {
		this.idPantalla = idPantalla;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSrc() {
		return this.src;
	}

	public void setSrc(String src) {
		this.src = src;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairPantallaUsuarios() {
		return this.sairPantallaUsuarios;
	}

	public void setSairPantallaUsuarios(Set sairPantallaUsuarios) {
		this.sairPantallaUsuarios = sairPantallaUsuarios;
	}

}
