package ec.com.rgt.sair.hbm;

// Generated 01/12/2016 12:38:36 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriRiesgo generated by hbmjava
 */
public class SairBriRiesgo implements java.io.Serializable {

	private BigDecimal idRiesgo;
	private String nombre;
	private String estado;
	private Set sairBriBriefs = new HashSet(0);

	public SairBriRiesgo() {
	}

	public SairBriRiesgo(BigDecimal idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public SairBriRiesgo(BigDecimal idRiesgo, String nombre, String estado,
			Set sairBriBriefs) {
		this.idRiesgo = idRiesgo;
		this.nombre = nombre;
		this.estado = estado;
		this.sairBriBriefs = sairBriBriefs;
	}

	public BigDecimal getIdRiesgo() {
		return this.idRiesgo;
	}

	public void setIdRiesgo(BigDecimal idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairBriBriefs() {
		return this.sairBriBriefs;
	}

	public void setSairBriBriefs(Set sairBriBriefs) {
		this.sairBriBriefs = sairBriBriefs;
	}

}
