package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairSecuencialDocumentoId generated by hbmjava
 */
public class SairSecuencialDocumentoId implements java.io.Serializable {

	private BigDecimal idSecuencialDocumento;
	private BigDecimal idTipoDocumento;
	private BigDecimal idSubArea;

	public SairSecuencialDocumentoId() {
	}

	public SairSecuencialDocumentoId(BigDecimal idSecuencialDocumento,
			BigDecimal idTipoDocumento, BigDecimal idSubArea) {
		this.idSecuencialDocumento = idSecuencialDocumento;
		this.idTipoDocumento = idTipoDocumento;
		this.idSubArea = idSubArea;
	}

	public BigDecimal getIdSecuencialDocumento() {
		return this.idSecuencialDocumento;
	}

	public void setIdSecuencialDocumento(BigDecimal idSecuencialDocumento) {
		this.idSecuencialDocumento = idSecuencialDocumento;
	}

	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public BigDecimal getIdSubArea() {
		return this.idSubArea;
	}

	public void setIdSubArea(BigDecimal idSubArea) {
		this.idSubArea = idSubArea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairSecuencialDocumentoId))
			return false;
		SairSecuencialDocumentoId castOther = (SairSecuencialDocumentoId) other;

		return ((this.getIdSecuencialDocumento() == castOther
				.getIdSecuencialDocumento()) || (this
				.getIdSecuencialDocumento() != null
				&& castOther.getIdSecuencialDocumento() != null && this
				.getIdSecuencialDocumento().equals(
						castOther.getIdSecuencialDocumento())))
				&& ((this.getIdTipoDocumento() == castOther
						.getIdTipoDocumento()) || (this.getIdTipoDocumento() != null
						&& castOther.getIdTipoDocumento() != null && this
						.getIdTipoDocumento().equals(
								castOther.getIdTipoDocumento())))
				&& ((this.getIdSubArea() == castOther.getIdSubArea()) || (this
						.getIdSubArea() != null
						&& castOther.getIdSubArea() != null && this
						.getIdSubArea().equals(castOther.getIdSubArea())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdSecuencialDocumento() == null ? 0 : this
						.getIdSecuencialDocumento().hashCode());
		result = 37
				* result
				+ (getIdTipoDocumento() == null ? 0 : this.getIdTipoDocumento()
						.hashCode());
		result = 37 * result
				+ (getIdSubArea() == null ? 0 : this.getIdSubArea().hashCode());
		return result;
	}

}
