package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocRiesgoInforme generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocRiesgoInforme implements java.io.Serializable {

	private BigDecimal idRiesgoInforme;
	private SairDocRiesgoDocumento sairDocRiesgoDocumento;
	private SairDocInformes sairDocInformes;
	private SairEstadosPrincipal sairEstadosPrincipal;
	private BigDecimal idEstadoComp;

	public SairDocRiesgoInforme() {
	}

	public SairDocRiesgoInforme(BigDecimal idRiesgoInforme,
			SairDocRiesgoDocumento sairDocRiesgoDocumento,
			SairDocInformes sairDocInformes,
			SairEstadosPrincipal sairEstadosPrincipal, BigDecimal idEstadoComp) {
		this.idRiesgoInforme = idRiesgoInforme;
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
		this.sairDocInformes = sairDocInformes;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
		this.idEstadoComp = idEstadoComp;
	}

	public BigDecimal getIdRiesgoInforme() {
		return this.idRiesgoInforme;
	}

	public void setIdRiesgoInforme(BigDecimal idRiesgoInforme) {
		this.idRiesgoInforme = idRiesgoInforme;
	}

	public SairDocRiesgoDocumento getSairDocRiesgoDocumento() {
		return this.sairDocRiesgoDocumento;
	}

	public void setSairDocRiesgoDocumento(
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

	public SairDocInformes getSairDocInformes() {
		return this.sairDocInformes;
	}

	public void setSairDocInformes(SairDocInformes sairDocInformes) {
		this.sairDocInformes = sairDocInformes;
	}

	public SairEstadosPrincipal getSairEstadosPrincipal() {
		return this.sairEstadosPrincipal;
	}

	public void setSairEstadosPrincipal(
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	public BigDecimal getIdEstadoComp() {
		return this.idEstadoComp;
	}

	public void setIdEstadoComp(BigDecimal idEstadoComp) {
		this.idEstadoComp = idEstadoComp;
	}

}
