package ec.com.rgt.sair.hbm;
// Generated 13/01/2017 15:02:53 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairActaTipo generated by hbm2java
 */
public class SairActaTipo implements java.io.Serializable {

	private BigDecimal idTipo;
	private String nombre;
	private String descripcion;
	private String estado;
	private Set sairActaProyectos = new HashSet(0);

	public SairActaTipo() {
	}

	public SairActaTipo(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public SairActaTipo(BigDecimal idTipo, String nombre, String descripcion, String estado, Set sairActaProyectos) {
		this.idTipo = idTipo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.sairActaProyectos = sairActaProyectos;
	}

	public BigDecimal getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairActaProyectos() {
		return this.sairActaProyectos;
	}

	public void setSairActaProyectos(Set sairActaProyectos) {
		this.sairActaProyectos = sairActaProyectos;
	}

}
