package ec.com.rgt.sair.hbm;

// Generated 12-ago-2014 11:50:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairGerente generated by hbmjava
 */
public class SairGerente implements java.io.Serializable {

	private BigDecimal idGerente;
	private String nombre;
	private String usuario,idUsuarioAic,idLocalidad;
	private BigDecimal idJefe;
	private BigDecimal idDepartamento;
	private String cargo;
	private String apellido;
	private String estado;
	private String nombresCompletos;
	private BigDecimal idArea;
	private String provincia,cedula,exepcion,email;
	private BigDecimal codigosf;
	
	
	public BigDecimal getCodigosf() {
		return codigosf;
	}

	public void setCodigo_sf(BigDecimal codigosf) {
		this.codigosf = codigosf;
	}


    
	
	
	public SairGerente() {
	}

	public SairGerente(BigDecimal idGerente) {
		this.idGerente = idGerente;
	}

	public SairGerente(BigDecimal idGerente, String nombre, String usuario,
			BigDecimal idJefe, BigDecimal idDepartamento, String cargo,
			String apellido, String estado, String nombresCompletos,
			BigDecimal idArea,String provincia,String cedula,String idUsuarioAic,String exepcion,String idLocalidad,String email,BigDecimal codigosf) {
		this.idGerente = idGerente;
		this.nombre = nombre;
		this.usuario = usuario;
		this.idJefe = idJefe;
		this.idDepartamento = idDepartamento;
		this.cargo = cargo;
		this.apellido = apellido;
		this.estado = estado;
		this.nombresCompletos = nombresCompletos;
		this.idArea = idArea;
		this.provincia = provincia;
		this.cedula = cedula;
		this.idUsuarioAic = idUsuarioAic;
		this.exepcion= exepcion;
		this.idLocalidad = idLocalidad;
		this.email =email;
		this.codigosf=codigosf;
	}
	
	
		
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getIdLocalidad() {
		return idLocalidad;
	}

	public void setIdLocalidad(String idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public String getExepcion() {
		return exepcion;
	}

	public void setExepcion(String exepcion) {
		this.exepcion = exepcion;
	}

	public String getIdUsuarioAic() {
		return idUsuarioAic;
	}

	public void setIdUsuarioAic(String idUsuarioAic) {
		this.idUsuarioAic = idUsuarioAic;
	}

	public String getCedula() {
		return cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public BigDecimal getIdGerente() {
		return this.idGerente;
	}

	public void setIdGerente(BigDecimal idGerente) {
		this.idGerente = idGerente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public BigDecimal getIdJefe() {
		return this.idJefe;
	}

	public void setIdJefe(BigDecimal idJefe) {
		this.idJefe = idJefe;
	}

	public BigDecimal getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(BigDecimal idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombresCompletos() {
		return this.nombresCompletos;
	}

	public void setNombresCompletos(String nombresCompletos) {
		this.nombresCompletos = nombresCompletos;
	}

	public BigDecimal getIdArea() {
		return this.idArea;
	}

	public void setIdArea(BigDecimal idArea) {
		this.idArea = idArea;
	}


	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}


	

}
