package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import ec.com.rgt.sair.hbm.SairDocImpacto;
import ec.com.rgt.sair.hbm.SairDocPrioridad;
import ec.com.rgt.sair.hbm.SairDocReservacionCodigo;

/**
 * SairDocConclusionDocumento generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocConclusionDocumento implements java.io.Serializable {

	private BigDecimal idConclusionDocumento;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairDocImpacto sairDocImpacto;
	private SairDocPrioridad sairDocPrioridad;
	private BigDecimal idComentarioPadre;
	private String usuarioIngreso;
	private String textoComentario;
	private BigDecimal calificacion,rc,idTemp;
	private String prioridad,estado;
	private Date fechaIngreso,fechaActualiza;
	private SairDocTipoHallazgo sairDocTipoHallazgo;
	private SairDocTipoEvento sairDocTipoEvento;
	private BigDecimal eventoAfectado;
	private String tipoImpacto;
	private BigDecimal valorDetectado;
	private BigDecimal valorADevolver;

	public BigDecimal getIdTemp() {
		return idTemp;
	}

	public void setIdTemp(BigDecimal idTemp) {
		this.idTemp = idTemp;
	}

	public SairDocConclusionDocumento() {
	}
	
	public Date getFechaActualiza() {
		return fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public SairDocConclusionDocumento(BigDecimal idConclusionDocumento,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.idConclusionDocumento = idConclusionDocumento;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairDocConclusionDocumento(BigDecimal idConclusionDocumento,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairDocImpacto sairDocImpacto, SairDocPrioridad sairDocPrioridad,
			String usuarioIngreso, String textoComentario,
			BigDecimal calificacion,String prioridad,
			Date fechaIngreso, BigDecimal idComentarioPadre,String estado,BigDecimal rc,BigDecimal idTemp,Date fechaActualiza,
			SairDocTipoHallazgo sairDocTipoHallazgo, SairDocTipoEvento sairDocTipoEvento, BigDecimal eventoAfectado, String tipoImpacto, 
			BigDecimal valorDetectado, BigDecimal valorADevolver) {
		this.idConclusionDocumento = idConclusionDocumento;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairDocImpacto = sairDocImpacto;
		this.sairDocPrioridad = sairDocPrioridad;
		this.idComentarioPadre = idComentarioPadre;
		this.usuarioIngreso = usuarioIngreso;
		this.textoComentario = textoComentario;
		this.calificacion = calificacion;
		this.fechaIngreso = fechaIngreso;
		this.prioridad = prioridad;
		this.estado = estado;
		this.rc = rc;
		this.idTemp = idTemp;
		this.fechaActualiza = fechaActualiza;
		this.sairDocTipoHallazgo = sairDocTipoHallazgo;
		this.sairDocTipoEvento = sairDocTipoEvento;
		this.eventoAfectado = eventoAfectado;
		this.tipoImpacto = tipoImpacto;
		this.valorDetectado = valorDetectado;
		this.valorADevolver = valorADevolver;
	}
	
	
	public BigDecimal getRc() {
		return rc;
	}

	public void setRc(BigDecimal rc) {
		this.rc = rc;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getIdComentarioPadre() {
		return idComentarioPadre;
	}

	public void setIdComentarioPadre(BigDecimal idComentarioPadre) {
		this.idComentarioPadre = idComentarioPadre;
	}

	public BigDecimal getIdConclusionDocumento() {
		return this.idConclusionDocumento;
	}

	public void setIdConclusionDocumento(BigDecimal idConclusionDocumento) {
		this.idConclusionDocumento = idConclusionDocumento;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	

	public String getTextoComentario() {
		return this.textoComentario;
	}

	public void setTextoComentario(String textoComentario) {
		this.textoComentario = textoComentario;
	}

	public BigDecimal getCalificacion() {
		return this.calificacion;
	}

	public void setCalificacion(BigDecimal calificacion) {
		this.calificacion = calificacion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public SairDocImpacto getSairDocImpacto() {
		return sairDocImpacto;
	}

	public void setSairDocImpacto(SairDocImpacto sairDocImpacto) {
		this.sairDocImpacto = sairDocImpacto;
	}

	public SairDocPrioridad getSairDocPrioridad() {
		return sairDocPrioridad;
	}

	public void setSairDocPrioridad(SairDocPrioridad sairDocPrioridad) {
		this.sairDocPrioridad = sairDocPrioridad;
	}

	public String getUsuarioIngreso() {
		return usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public String getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}
	
	public SairDocTipoHallazgo getSairDocTipoHallazgo() {
		return sairDocTipoHallazgo;
	}

	public void setSairDocTipoHallazgo(SairDocTipoHallazgo sairDocTipoHallazgo) {
		this.sairDocTipoHallazgo = sairDocTipoHallazgo;
	}

	public SairDocTipoEvento getSairDocTipoEvento() {
		return sairDocTipoEvento;
	}

	public void setSairDocTipoEvento(SairDocTipoEvento sairDocTipoEvento) {
		this.sairDocTipoEvento = sairDocTipoEvento;
	}

	public BigDecimal getEventoAfectado() {
		return eventoAfectado;
	}

	public void setEventoAfectado(BigDecimal eventoAfectado) {
		this.eventoAfectado = eventoAfectado;
	}

	public String getTipoImpacto() {
		return tipoImpacto;
	}

	public void setTipoImpacto(String tipoImpacto) {
		this.tipoImpacto = tipoImpacto;
	}

	public BigDecimal getValorDetectado() {
		return valorDetectado;
	}

	public void setValorDetectado(BigDecimal valorDetectado) {
		this.valorDetectado = valorDetectado;
	}

	public BigDecimal getValorADevolver() {
		return valorADevolver;
	}

	public void setValorADevolver(BigDecimal valorADevolver) {
		this.valorADevolver = valorADevolver;
	}


}
