package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairPermisosUsuarios generated by hbmjava
 */
public class SairPermisosUsuarios implements java.io.Serializable {

	private BigDecimal idPermiso;
	private String usuarioPadre;
	private String usuarioHijo;
	private String usuarioIngreso;
	private Date fechaIngreso;
	private String estado;

	public SairPermisosUsuarios() {
	}

	public SairPermisosUsuarios(BigDecimal idPermiso) {
		this.idPermiso = idPermiso;
	}

	public SairPermisosUsuarios(BigDecimal idPermiso, String usuarioPadre,
			String usuarioHijo, String usuarioIngreso, Date fechaIngreso,
			String estado) {
		this.idPermiso = idPermiso;
		this.usuarioPadre = usuarioPadre;
		this.usuarioHijo = usuarioHijo;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
	}

	public BigDecimal getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(BigDecimal idPermiso) {
		this.idPermiso = idPermiso;
	}

	public String getUsuarioPadre() {
		return this.usuarioPadre;
	}

	public void setUsuarioPadre(String usuarioPadre) {
		this.usuarioPadre = usuarioPadre;
	}

	public String getUsuarioHijo() {
		return this.usuarioHijo;
	}

	public void setUsuarioHijo(String usuarioHijo) {
		this.usuarioHijo = usuarioHijo;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
