package ec.com.rgt.sair.hbm;
// Generated 21/08/2017 14:58:01 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairPrioridad generated by hbm2java
 */
public class SairPrioridad implements java.io.Serializable {

	private BigDecimal idPrioridad;
	private String prioridad;
	private BigDecimal valorRecuperar;
	private BigDecimal valorDevolver;
	private BigDecimal casosRecuperar;
	private BigDecimal casosDevolver;
	private BigDecimal casosSinAfectacion;
	private String errorOperativo;
	private String errorTecnologico;
	private String usuario;
	private Date fechaIngreso;

	public SairPrioridad() {
	}

	public SairPrioridad(BigDecimal idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public SairPrioridad(BigDecimal idPrioridad, String prioridad, BigDecimal valorRecuperar, BigDecimal valorDevolver,
			BigDecimal casosRecuperar, BigDecimal casosDevolver, BigDecimal casosSinAfectacion, String errorOperativo,
			String errorTecnologico, String usuario, Date fechaIngreso) {
		this.idPrioridad = idPrioridad;
		this.prioridad = prioridad;
		this.valorRecuperar = valorRecuperar;
		this.valorDevolver = valorDevolver;
		this.casosRecuperar = casosRecuperar;
		this.casosDevolver = casosDevolver;
		this.casosSinAfectacion = casosSinAfectacion;
		this.errorOperativo = errorOperativo;
		this.errorTecnologico = errorTecnologico;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public BigDecimal getIdPrioridad() {
		return this.idPrioridad;
	}

	public void setIdPrioridad(BigDecimal idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public String getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public BigDecimal getValorRecuperar() {
		return this.valorRecuperar;
	}

	public void setValorRecuperar(BigDecimal valorRecuperar) {
		this.valorRecuperar = valorRecuperar;
	}

	public BigDecimal getValorDevolver() {
		return this.valorDevolver;
	}

	public void setValorDevolver(BigDecimal valorDevolver) {
		this.valorDevolver = valorDevolver;
	}

	public BigDecimal getCasosRecuperar() {
		return this.casosRecuperar;
	}

	public void setCasosRecuperar(BigDecimal casosRecuperar) {
		this.casosRecuperar = casosRecuperar;
	}

	public BigDecimal getCasosDevolver() {
		return this.casosDevolver;
	}

	public void setCasosDevolver(BigDecimal casosDevolver) {
		this.casosDevolver = casosDevolver;
	}

	public BigDecimal getCasosSinAfectacion() {
		return this.casosSinAfectacion;
	}

	public void setCasosSinAfectacion(BigDecimal casosSinAfectacion) {
		this.casosSinAfectacion = casosSinAfectacion;
	}

	public String getErrorOperativo() {
		return this.errorOperativo;
	}

	public void setErrorOperativo(String errorOperativo) {
		this.errorOperativo = errorOperativo;
	}

	public String getErrorTecnologico() {
		return this.errorTecnologico;
	}

	public void setErrorTecnologico(String errorTecnologico) {
		this.errorTecnologico = errorTecnologico;
	}

}
