package ec.com.rgt.sair.hbm;

// Generated 08/10/2013 12:21:13 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairParametros generated by hbmjava
 */
public class SairParametros implements java.io.Serializable {

	private BigDecimal idParametro;
	private String nombre;
	private String detalle;
	private String valor;
	private String usuarioIngreso;
	private Date fechaInicio;
	private String usuarioModificacion;
	private Date fechaModificacion;
	private String estado;
	private BigDecimal valorNumerico;
	private BigDecimal idPadre;

	public SairParametros() {
	}

	public SairParametros(BigDecimal idParametro, String nombre,
			String detalle, String usuarioIngreso, Date fechaInicio,
			String estado) {
		this.idParametro = idParametro;
		this.nombre = nombre;
		this.detalle = detalle;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public SairParametros(BigDecimal idParametro, String nombre,
			String detalle, String valor, String usuarioIngreso,
			Date fechaInicio, String usuarioModificacion,
			Date fechaModificacion, String estado, BigDecimal valorNumerico,
			BigDecimal idPadre) {
		this.idParametro = idParametro;
		this.nombre = nombre;
		this.detalle = detalle;
		this.valor = valor;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaInicio = fechaInicio;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaModificacion = fechaModificacion;
		this.estado = estado;
		this.valorNumerico = valorNumerico;
		this.idPadre = idPadre;
	}

	public BigDecimal getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(BigDecimal idParametro) {
		this.idParametro = idParametro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getValorNumerico() {
		return this.valorNumerico;
	}

	public void setValorNumerico(BigDecimal valorNumerico) {
		this.valorNumerico = valorNumerico;
	}

	public BigDecimal getIdPadre() {
		return this.idPadre;
	}

	public void setIdPadre(BigDecimal idPadre) {
		this.idPadre = idPadre;
	}

}
