package ec.com.rgt.sair.hbm;

// Generated 08-may-2014 14:31:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairTipoLog generated by hbmjava
 */
public class SairTipoLog implements java.io.Serializable {

	private BigDecimal idTipo;
	private String nombre;
	private String descripcion;
	private String estado;
	private Set sairLogs = new HashSet(0);

	public SairTipoLog() {
	}

	public SairTipoLog(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public SairTipoLog(BigDecimal idTipo, String nombre, String descripcion,
			String estado, Set sairLogs) {
		this.idTipo = idTipo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.sairLogs = sairLogs;
	}

	public BigDecimal getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairLogs() {
		return this.sairLogs;
	}

	public void setSairLogs(Set sairLogs) {
		this.sairLogs = sairLogs;
	}

}
