package ec.com.rgt.sair.hbm;
// Generated 13/01/2017 15:02:53 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * SairActaCorresponsable generated by hbm2java
 */
public class SairActaCorresponsable implements java.io.Serializable {

	private SairActaCorresponsableId id;
	private SairActaProyecto sairActaProyecto;
	private Date fechaIngreso;

	public SairActaCorresponsable() {
	}

	public SairActaCorresponsable(SairActaCorresponsableId id, SairActaProyecto sairActaProyecto) {
		this.id = id;
		this.sairActaProyecto = sairActaProyecto;
	}

	public SairActaCorresponsable(SairActaCorresponsableId id, SairActaProyecto sairActaProyecto, Date fechaIngreso) {
		this.id = id;
		this.sairActaProyecto = sairActaProyecto;
		this.fechaIngreso = fechaIngreso;
	}

	public SairActaCorresponsableId getId() {
		return this.id;
	}

	public void setId(SairActaCorresponsableId id) {
		this.id = id;
	}

	public SairActaProyecto getSairActaProyecto() {
		return this.sairActaProyecto;
	}

	public void setSairActaProyecto(SairActaProyecto sairActaProyecto) {
		this.sairActaProyecto = sairActaProyecto;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
