package ec.com.rgt.sair.hbm;

// Generated 02-oct-2014 10:17:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocPrioridad generated by hbmjava
 */
public class SairDocPrioridad implements java.io.Serializable {

	private BigDecimal idPrioridad;
	private String nombre;
	private String estado;

	public SairDocPrioridad() {
	}

	public SairDocPrioridad(BigDecimal idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public SairDocPrioridad(BigDecimal idPrioridad, String nombre) {
		this.idPrioridad = idPrioridad;
		this.nombre = nombre;
		this.estado = estado;
	}

	public BigDecimal getIdPrioridad() {
		return this.idPrioridad;
	}

	public void setIdPrioridad(BigDecimal idPrioridad) {
		this.idPrioridad = idPrioridad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
