package ec.com.rgt.sair.hbm;
// Generated 13/01/2017 15:02:53 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * SairActaCorresponsableId generated by hbm2java
 */
public class SairActaCorresponsableId implements java.io.Serializable {

	private String idCorresponsable;
	private BigDecimal idProyecto;

	public SairActaCorresponsableId() {
	}

	public SairActaCorresponsableId(String idCorresponsable, BigDecimal idProyecto) {
		this.idCorresponsable = idCorresponsable;
		this.idProyecto = idProyecto;
	}

	public String getIdCorresponsable() {
		return this.idCorresponsable;
	}

	public void setIdCorresponsable(String idCorresponsable) {
		this.idCorresponsable = idCorresponsable;
	}

	public BigDecimal getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(BigDecimal idProyecto) {
		this.idProyecto = idProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairActaCorresponsableId))
			return false;
		SairActaCorresponsableId castOther = (SairActaCorresponsableId) other;

		return ((this.getIdCorresponsable() == castOther.getIdCorresponsable())
				|| (this.getIdCorresponsable() != null && castOther.getIdCorresponsable() != null
						&& this.getIdCorresponsable().equals(castOther.getIdCorresponsable())))
				&& ((this.getIdProyecto() == castOther.getIdProyecto())
						|| (this.getIdProyecto() != null && castOther.getIdProyecto() != null
								&& this.getIdProyecto().equals(castOther.getIdProyecto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCorresponsable() == null ? 0 : this.getIdCorresponsable().hashCode());
		result = 37 * result + (getIdProyecto() == null ? 0 : this.getIdProyecto().hashCode());
		return result;
	}

}
