package ec.com.rgt.sair.hbm;

import java.io.Serializable;

// Generated 12-ago-2014 15:05:48 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairObservaciones generated by hbmjava
 */
public class SairObservaciones implements Serializable{
	private static final long serialVersionUID =1l;
	private BigDecimal idObservacion;
	private SairAreasAdam sairAreasAdam;
	private SairObsComentarioAic sairObsComentarioAic;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairIncTipo sairIncTipo;
	private SairObsDetallesFaltas sairObsDetallesFaltas;
	private SairSubArea sairSubArea;
	private SairArea sairArea;
	private SairObsTipoFalta sairObsTipoFalta;
	private SairCiudad sairCiudad;
	private SairObsAccionAdm sairObsAccionAdm;
	private SairRecRecomendacion sairRecRecomendacion;
	private SairObsTipoJustificacion sairObsTipoJustificacion;
	private String idUsuarioAic;
	private String idOperador;
	private String idGerente;
	private String idSupervisor;
	private String cuenta;
	private String telefono;
	private Date fechaCreacion,fechaRespAud,fechaRespOpe;
	private String observacion,idLocalidad;
	private BigDecimal valor;
	private String mesPeriodo;
	private BigDecimal anioPeriodo;
	private String estado;
	private Date fechaActualiza;
	private String codIncidencia;
	private String valorAsociado,UsuarioAct;
	private String dat1;
	private String dat2;
	private String dat3;
	private String dat4;
	private String dat5;
	private String dat6;
	private String dat7;
	private String dat8;
	private String dat9;
	private String dat10;
	private String dat11;
	private String dat12;
	private String dat13;
	private String dat14;
	private String dat15;
	private String dat16;

    private Date fechaCreacion1;
    private Date fechaRespOpe1;
    
	

	public SairObservaciones() {
	}


	public SairObservaciones(String dat1) {
		super();
		this.dat1 = dat1;
	}
	
	public SairObservaciones(BigDecimal idObservacion) {
		this.idObservacion = idObservacion;
	}

	public SairObservaciones(BigDecimal idObservacion,
			SairAreasAdam sairAreasAdam,
			SairObsComentarioAic sairObsComentarioAic,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairIncTipo sairIncTipo,
			SairObsDetallesFaltas sairObsDetallesFaltas,
			SairSubArea sairSubArea, SairArea sairArea,
			SairObsTipoFalta sairObsTipoFalta, SairCiudad sairCiudad,
			SairObsAccionAdm sairObsAccionAdm,
			SairRecRecomendacion sairRecRecomendacion,
			String idLocalidad,
			SairObsTipoJustificacion sairObsTipoJustificacion,
			String idUsuarioAic, String idOperador, String idGerente,
			String idSupervisor, String cuenta, String telefono,
			Date fechaCreacion, Date fechaRespAud, Date fechaRespOpe,
			String observacion, BigDecimal valor, String mesPeriodo,
			BigDecimal anioPeriodo, String estado, Date fechaActualiza,
			String codIncidencia, String valorAsociado,String UsuarioAct) {
		super();
		this.idObservacion = idObservacion;
		this.sairAreasAdam = sairAreasAdam;
		this.sairObsComentarioAic = sairObsComentarioAic;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairIncTipo = sairIncTipo;
		this.sairObsDetallesFaltas = sairObsDetallesFaltas;
		this.sairSubArea = sairSubArea;
		this.sairArea = sairArea;
		this.sairObsTipoFalta = sairObsTipoFalta;
		this.sairCiudad = sairCiudad;
		this.sairObsAccionAdm = sairObsAccionAdm;
		this.sairRecRecomendacion = sairRecRecomendacion;
		this.idLocalidad = idLocalidad;
		this.sairObsTipoJustificacion = sairObsTipoJustificacion;
		this.idUsuarioAic = idUsuarioAic;
		this.idOperador = idOperador;
		this.idGerente = idGerente;
		this.idSupervisor = idSupervisor;
		this.cuenta = cuenta;
		this.telefono = telefono;
		this.fechaCreacion = fechaCreacion;
		this.fechaRespAud = fechaRespAud;
		this.fechaRespOpe = fechaRespOpe;
		this.observacion = observacion;
		this.valor = valor;
		this.mesPeriodo = mesPeriodo;
		this.anioPeriodo = anioPeriodo;
		this.estado = estado;
		this.fechaActualiza = fechaActualiza;
		this.codIncidencia = codIncidencia;
		this.valorAsociado = valorAsociado;
		this.UsuarioAct = UsuarioAct;
	}

	
	
	public SairObservaciones(String dat1, String dat2, String dat3, String dat4, String dat5, String dat6, String dat7,
			String dat8, String dat9, String dat10, String dat11, String dat12, String dat13, String dat14,
			String dat15, String dat16) {
		super();
		this.dat1 = dat1;
		this.dat2 = dat2;
		this.dat3 = dat3;
		this.dat4 = dat4;
		this.dat5 = dat5;
		this.dat6 = dat6;
		this.dat7 = dat7;
		this.dat8 = dat8;
		this.dat9 = dat9;
		this.dat10 = dat10;
		this.dat11 = dat11;
		this.dat12 = dat12;
		this.dat13 = dat13;
		this.dat14 = dat14;
		this.dat15 = dat15;
		this.dat16 = dat16;
	}

	public String getUsuarioAct() {
		return UsuarioAct;
	}

	public void setUsuarioAct(String usuarioAct) {
		UsuarioAct = usuarioAct;
	}

	public String getIdLocalidad() {
		return idLocalidad;
	}

	public void setIdLocalidad(String idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public SairObsTipoJustificacion getSairObsTipoJustificacion() {
		return sairObsTipoJustificacion;
	}

	public void setSairObsTipoJustificacion(
			SairObsTipoJustificacion sairObsTipoJustificacion) {
		this.sairObsTipoJustificacion = sairObsTipoJustificacion;
	}

	public Date getFechaRespAud() {
		return fechaRespAud;
	}

	public void setFechaRespAud(Date fechaRespAud) {
		this.fechaRespAud = fechaRespAud;
	}

	public Date getFechaRespOpe() {
		return fechaRespOpe;
	}

	public void setFechaRespOpe(Date fechaRespOpe) {
		this.fechaRespOpe = fechaRespOpe;
	}

	public SairRecRecomendacion getSairRecRecomendacion() {
		return sairRecRecomendacion;
	}

	public void setSairRecRecomendacion(SairRecRecomendacion sairRecRecomendacion) {
		this.sairRecRecomendacion = sairRecRecomendacion;
	}

	public BigDecimal getIdObservacion() {
		return this.idObservacion;
	}

	public void setIdObservacion(BigDecimal idObservacion) {
		this.idObservacion = idObservacion;
	}

	public SairAreasAdam getSairAreasAdam() {
		return this.sairAreasAdam;
	}

	public void setSairAreasAdam(SairAreasAdam sairAreasAdam) {
		this.sairAreasAdam = sairAreasAdam;
	}
	
	public String getCodIncidencia() {
		return codIncidencia;
	}

	public void setCodIncidencia(String codIncidencia) {
		this.codIncidencia = codIncidencia;
	}

	public SairObsComentarioAic getSairObsComentarioAic() {
		return this.sairObsComentarioAic;
	}

	public void setSairObsComentarioAic(
			SairObsComentarioAic sairObsComentarioAic) {
		this.sairObsComentarioAic = sairObsComentarioAic;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairIncTipo getSairIncTipo() {
		return this.sairIncTipo;
	}

	public void setSairIncTipo(SairIncTipo sairIncTipo) {
		this.sairIncTipo = sairIncTipo;
	}

	public SairObsDetallesFaltas getSairObsDetallesFaltas() {
		return this.sairObsDetallesFaltas;
	}

	public void setSairObsDetallesFaltas(
			SairObsDetallesFaltas sairObsDetallesFaltas) {
		this.sairObsDetallesFaltas = sairObsDetallesFaltas;
	}

	public SairSubArea getSairSubArea() {
		return this.sairSubArea;
	}

	public void setSairSubArea(SairSubArea sairSubArea) {
		this.sairSubArea = sairSubArea;
	}

	public SairArea getSairArea() {
		return this.sairArea;
	}

	public void setSairArea(SairArea sairArea) {
		this.sairArea = sairArea;
	}

	public SairObsTipoFalta getSairObsTipoFalta() {
		return this.sairObsTipoFalta;
	}

	public void setSairObsTipoFalta(SairObsTipoFalta sairObsTipoFalta) {
		this.sairObsTipoFalta = sairObsTipoFalta;
	}

	public SairCiudad getSairCiudad() {
		return this.sairCiudad;
	}

	public void setSairCiudad(SairCiudad sairCiudad) {
		this.sairCiudad = sairCiudad;
	}

	public SairObsAccionAdm getSairObsAccionAdm() {
		return this.sairObsAccionAdm;
	}

	public void setSairObsAccionAdm(SairObsAccionAdm sairObsAccionAdm) {
		this.sairObsAccionAdm = sairObsAccionAdm;
	}

	public String getIdUsuarioAic() {
		return this.idUsuarioAic;
	}

	public void setIdUsuarioAic(String idUsuarioAic) {
		this.idUsuarioAic = idUsuarioAic;
	}

	public String getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(String idOperador) {
		this.idOperador = idOperador;
	}

	public String getIdGerente() {
		return this.idGerente;
	}

	public void setIdGerente(String idGerente) {
		this.idGerente = idGerente;
	}

	public String getIdSupervisor() {
		return this.idSupervisor;
	}

	public void setIdSupervisor(String idSupervisor) {
		this.idSupervisor = idSupervisor;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getMesPeriodo() {
		return this.mesPeriodo;
	}

	public void setMesPeriodo(String mesPeriodo) {
		this.mesPeriodo = mesPeriodo;
	}

	public BigDecimal getAnioPeriodo() {
		return this.anioPeriodo;
	}

	public void setAnioPeriodo(BigDecimal anioPeriodo) {
		this.anioPeriodo = anioPeriodo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}


	public String getValorAsociado() {
		return this.valorAsociado;
	}

	public void setValorAsociado(String valorAsociado) {
		this.valorAsociado = valorAsociado;
	}

	//MARIO 
	public String getDat1() {
		return dat1;
	}

	public void setDat1(String dat1) {
		this.dat1 = dat1;
	}

	public String getDat2() {
		return dat2;
	}

	public void setDat2(String dat2) {
		this.dat2 = dat2;
	}

	public String getDat3() {
		return dat3;
	}

	public void setDat3(String dat3) {
		this.dat3 = dat3;
	}

	public String getDat4() {
		return dat4;
	}

	public void setDat4(String dat4) {
		this.dat4 = dat4;
	}

	public String getDat5() {
		return dat5;
	}

	public void setDat5(String dat5) {
		this.dat5 = dat5;
	}

	public String getDat6() {
		return dat6;
	}

	public void setDat6(String dat6) {
		this.dat6 = dat6;
	}

	public String getDat7() {
		return dat7;
	}

	public void setDat7(String dat7) {
		this.dat7 = dat7;
	}

	public String getDat8() {
		return dat8;
	}

	public void setDat8(String dat8) {
		this.dat8 = dat8;
	}

	public String getDat9() {
		return dat9;
	}

	public void setDat9(String dat9) {
		this.dat9 = dat9;
	}

	public String getDat10() {
		return dat10;
	}

	public void setDat10(String dat10) {
		this.dat10 = dat10;
	}

	public String getDat11() {
		return dat11;
	}

	public void setDat11(String dat11) {
		this.dat11 = dat11;
	}

	public String getDat12() {
		return dat12;
	}

	public void setDat12(String dat12) {
		this.dat12 = dat12;
	}

	public String getDat13() {
		return dat13;
	}

	public void setDat13(String dat13) {
		this.dat13 = dat13;
	}

	public String getDat14() {
		return dat14;
	}

	public void setDat14(String dat14) {
		this.dat14 = dat14;
	}

	public String getDat15() {
		return dat15;
	}

	public void setDat15(String dat15) {
		this.dat15 = dat15;
	}

	public String getDat16() {
		return dat16;
	}

	public void setDat16(String dat16) {
		this.dat16 = dat16;
	}


	public java.util.Date getFechaCreacion1() {
		return fechaCreacion1;
	}

	public void setFechaCreacion1(java.util.Date fechaCreacion1) {
		this.fechaCreacion1 = fechaCreacion1;
	}

	public java.util.Date getFechaRespOpe1() {
		return fechaRespOpe1;
	}

	public void setFechaRespOpe1(java.util.Date fechaRespOpe1) {
		this.fechaRespOpe1 = fechaRespOpe1;
	}
	
}
