package ec.com.rgt.sair.hbm;

// Generated 01/12/2016 12:38:36 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriAcciones generated by hbmjava
 */
public class SairBriAcciones implements java.io.Serializable {

	private BigDecimal idAccion,temp;
	private SairBriEstatus sairBriEstatus;
	private SairBriBrief sairBriBrief;
	private String accion;
	private Date fecha;
	private Set sairBriAccionAreas = new HashSet(0);

	public SairBriAcciones() {
	}

	public SairBriAcciones(BigDecimal idAccion) {
		this.idAccion = idAccion;
	}

	public SairBriAcciones(BigDecimal idAccion, SairBriEstatus sairBriEstatus,
			SairBriBrief sairBriBrief, String accion, Date fecha,BigDecimal temp,
			Set sairBriAccionAreas) {
		this.idAccion = idAccion;
		this.sairBriEstatus = sairBriEstatus;
		this.sairBriBrief = sairBriBrief;
		this.accion = accion;
		this.fecha = fecha;
		this.temp = temp;
		this.sairBriAccionAreas = sairBriAccionAreas;
	}

	public BigDecimal getIdAccion() {
		return this.idAccion;
	}

	public void setIdAccion(BigDecimal idAccion) {
		this.idAccion = idAccion;
	}

	public BigDecimal getTemp() {
		return temp;
	}

	public void setTemp(BigDecimal temp) {
		this.temp = temp;
	}

	public SairBriEstatus getSairBriEstatus() {
		return this.sairBriEstatus;
	}

	public void setSairBriEstatus(SairBriEstatus sairBriEstatus) {
		this.sairBriEstatus = sairBriEstatus;
	}

	public SairBriBrief getSairBriBrief() {
		return this.sairBriBrief;
	}

	public void setSairBriBrief(SairBriBrief sairBriBrief) {
		this.sairBriBrief = sairBriBrief;
	}

	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getSairBriAccionAreas() {
		return this.sairBriAccionAreas;
	}

	public void setSairBriAccionAreas(Set sairBriAccionAreas) {
		this.sairBriAccionAreas = sairBriAccionAreas;
	}

}
