package ec.com.rgt.sair.hbm;

// Generated 24-ago-2015 9:51:38 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairForumQuestions generated by hbmjava
 */
public class SairForumQuestions implements java.io.Serializable {

	private BigDecimal idQuestion;
	private Usuarios usuarios;
	private SairForumTag sairForumTag;
	private String pregunta;
	private String detalle;
	private Date fechaIngreso;
	private BigDecimal voto;
	private String estado;
	private Set sairForumRespuestas = new HashSet(0);

	public SairForumQuestions() {
	}

	public SairForumQuestions(BigDecimal idQuestion) {
		this.idQuestion = idQuestion;
	}

	public SairForumQuestions(BigDecimal idQuestion, Usuarios usuarios,
			SairForumTag sairForumTag, String pregunta, String detalle,
			Date fechaIngreso, BigDecimal voto, String estado,
			Set sairForumRespuestas) {
		this.idQuestion = idQuestion;
		this.usuarios = usuarios;
		this.sairForumTag = sairForumTag;
		this.pregunta = pregunta;
		this.detalle = detalle;
		this.fechaIngreso = fechaIngreso;
		this.voto = voto;
		this.estado = estado;
		this.sairForumRespuestas = sairForumRespuestas;
	}

	public BigDecimal getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(BigDecimal idQuestion) {
		this.idQuestion = idQuestion;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public SairForumTag getSairForumTag() {
		return this.sairForumTag;
	}

	public void setSairForumTag(SairForumTag sairForumTag) {
		this.sairForumTag = sairForumTag;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public BigDecimal getVoto() {
		return this.voto;
	}

	public void setVoto(BigDecimal voto) {
		this.voto = voto;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairForumRespuestas() {
		return this.sairForumRespuestas;
	}

	public void setSairForumRespuestas(Set sairForumRespuestas) {
		this.sairForumRespuestas = sairForumRespuestas;
	}

}
