package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;
//import ec.com.rgt.sair.controller.SanearString;

/**
 * SairDocMemorando generated by hbmjava
 */
@XmlRootElement
public class SairDocMemorando implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idMemorando,p,i,casosSinAfectacion;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairEstadosPrincipal sairEstadosPrincipal;
	private SairDocAjusteCorreccion sairDocAjusteCorreccion;
	private SairDocRiesgoDocumento sairDocRiesgoDocumento;
	private String asunto;
	private String antecedente;
	private Date fechaElaboracion;
	private Date fechaEmision;
	//private String imagen;
	private BigDecimal cantidadCasosRecuperar;
	private String errorOperativoTecnologico,errorTecnologico;
	private BigDecimal valorRecuperar;
	private BigDecimal valorDevolver;
	private BigDecimal cantidadCasosDevolver;
	private String usuarioActualizacion;
	private Date fechaActualizacion;
	private BigDecimal cantidadRecomendaciones;
	private String revisionSupervisor;
	private String revisionJefe;
	private BigDecimal idEstadoComp;
	private String estado;
	private String prioridadAjuste,prioridad;
	private String alcance;
	private String comentario;
	private Date fechaEmisionReal;
	//SanearString s =new SanearString();

	public SairDocMemorando() {
	}

	public SairDocMemorando(BigDecimal idMemorando) {
		this.idMemorando = idMemorando;
	}
	
	
	public BigDecimal getCasosSinAfectacion() {
		return casosSinAfectacion;
	}

	public void setCasosSinAfectacion(BigDecimal casosSinAfectacion) {
		this.casosSinAfectacion = casosSinAfectacion;
	}

	public String getErrorTecnologico() {
		return errorTecnologico;
	}

	public void setErrorTecnologico(String errorTecnologico) {
		this.errorTecnologico = errorTecnologico;
	}

	public SairDocMemorando(BigDecimal idMemorando, BigDecimal p, BigDecimal i,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairEstadosPrincipal sairEstadosPrincipal,
			SairDocAjusteCorreccion sairDocAjusteCorreccion,
			SairDocRiesgoDocumento sairDocRiesgoDocumento, String asunto,
			String antecedente, Date fechaElaboracion, Date fechaEmision,
			//String imagen, 
			BigDecimal cantidadCasosRecuperar,
			String errorOperativoTecnologico, BigDecimal valorRecuperar,
			BigDecimal valorDevolver, BigDecimal cantidadCasosDevolver,
			String usuarioActualizacion, Date fechaActualizacion,
			BigDecimal cantidadRecomendaciones, String revisionSupervisor,
			String revisionJefe, BigDecimal idEstadoComp, String estado,
			String prioridadAjuste, String alcance, String comentario,String prioridad,
			String errorTecnologico,BigDecimal casosSinAfectacion, Date fechaEmisionReal) {
		this.idMemorando = idMemorando;
		this.p = p;
		this.i = i;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
		this.sairDocAjusteCorreccion = sairDocAjusteCorreccion;
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
		this.asunto = asunto;
		this.antecedente = antecedente;
		this.fechaElaboracion = fechaElaboracion;
		this.fechaEmision = fechaEmision;
		//this.imagen = imagen;
		this.cantidadCasosRecuperar = cantidadCasosRecuperar;
		this.errorOperativoTecnologico = errorOperativoTecnologico;
		this.valorRecuperar = valorRecuperar;
		this.valorDevolver = valorDevolver;
		this.cantidadCasosDevolver = cantidadCasosDevolver;
		this.usuarioActualizacion = usuarioActualizacion;
		this.fechaActualizacion = fechaActualizacion;
		this.cantidadRecomendaciones = cantidadRecomendaciones;
		this.revisionSupervisor = revisionSupervisor;
		this.revisionJefe = revisionJefe;
		this.idEstadoComp = idEstadoComp;
		this.estado = estado;
		this.prioridadAjuste = prioridadAjuste;
		this.alcance = alcance;
		this.comentario = comentario;
		this.prioridad = prioridad;
		this.casosSinAfectacion= casosSinAfectacion;
		this.errorTecnologico = errorTecnologico;
		this.fechaEmisionReal = fechaEmisionReal;
	}

	
	public String getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public BigDecimal getP() {
		return p;
	}

	public void setP(BigDecimal p) {
		this.p = p;
	}

	public Date getFechaEmisionReal() {
		return fechaEmisionReal;
	}

	public void setFechaEmisionReal(Date fechaEmisionReal) {
		this.fechaEmisionReal = fechaEmisionReal;
	}

	public BigDecimal getI() {
		return i;
	}

	public void setI(BigDecimal i) {
		this.i = i;
	}

	public SairDocAjusteCorreccion getSairDocAjusteCorreccion() {
		return sairDocAjusteCorreccion;
	}

	public void setSairDocAjusteCorreccion(
			SairDocAjusteCorreccion sairDocAjusteCorreccion) {
		this.sairDocAjusteCorreccion = sairDocAjusteCorreccion;
	}

	public SairDocRiesgoDocumento getSairDocRiesgoDocumento() {
		return sairDocRiesgoDocumento;
	}

	public void setSairDocRiesgoDocumento(
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

	public BigDecimal getCantidadCasosRecuperar() {
		return cantidadCasosRecuperar;
	}

	public void setCantidadCasosRecuperar(BigDecimal cantidadCasosRecuperar) {
		this.cantidadCasosRecuperar = cantidadCasosRecuperar;
	}

	public String getErrorOperativoTecnologico() {
		return errorOperativoTecnologico;
	}

	public void setErrorOperativoTecnologico(String errorOperativoTecnologico) {
		this.errorOperativoTecnologico = errorOperativoTecnologico;
	}

	public BigDecimal getValorRecuperar() {
		return valorRecuperar;
	}

	public void setValorRecuperar(BigDecimal valorRecuperar) {
		this.valorRecuperar = valorRecuperar;
	}

	public BigDecimal getValorDevolver() {
		return valorDevolver;
	}

	public void setValorDevolver(BigDecimal valorDevolver) {
		this.valorDevolver = valorDevolver;
	}

	public BigDecimal getCantidadCasosDevolver() {
		return cantidadCasosDevolver;
	}

	public void setCantidadCasosDevolver(BigDecimal cantidadCasosDevolver) {
		this.cantidadCasosDevolver = cantidadCasosDevolver;
	}

	public String getPrioridadAjuste() {
		return prioridadAjuste;
	}

	public void setPrioridadAjuste(String prioridadAjuste) {
		this.prioridadAjuste = prioridadAjuste;
	}

	public String getAlcance() {
		return alcance;
	}

	public void setAlcance(String alcance) {
		this.alcance = alcance;
	}

	public BigDecimal getIdMemorando() {
		return this.idMemorando;
	}

	public void setIdMemorando(BigDecimal idMemorando) {
		this.idMemorando = idMemorando;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairEstadosPrincipal getSairEstadosPrincipal() {
		return this.sairEstadosPrincipal;
	}

	public void setSairEstadosPrincipal(
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	public String getAsunto() {
		//asunto=s.getString(asunto);
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getAntecedente() {
		return this.antecedente;
	}

	public void setAntecedente(String antecedente) {
		this.antecedente = antecedente;
	}

	public Date getFechaElaboracion() {
		return this.fechaElaboracion;
	}

	public void setFechaElaboracion(Date fechaElaboracion) {
		this.fechaElaboracion = fechaElaboracion;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	/*public String getImagen() {
		return this.imagen;
	}*/

	/*public void setImagen(String imagen) {
		this.imagen = imagen;
	}*/

	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public BigDecimal getCantidadRecomendaciones() {
		return this.cantidadRecomendaciones;
	}

	public void setCantidadRecomendaciones(BigDecimal cantidadRecomendaciones) {
		this.cantidadRecomendaciones = cantidadRecomendaciones;
	}

	public String getRevisionSupervisor() {
		return this.revisionSupervisor;
	}

	public void setRevisionSupervisor(String revisionSupervisor) {
		this.revisionSupervisor = revisionSupervisor;
	}

	public String getRevisionJefe() {
		return this.revisionJefe;
	}

	public void setRevisionJefe(String revisionJefe) {
		this.revisionJefe = revisionJefe;
	}

	public BigDecimal getIdEstadoComp() {
		return this.idEstadoComp;
	}

	public void setIdEstadoComp(BigDecimal idEstadoComp) {
		this.idEstadoComp = idEstadoComp;
	}
	
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getComentario() {
		//comentario=s.getString(comentario);
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}
}
