package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocRiesgoDocumento generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocRiesgoDocumento implements java.io.Serializable {

	private BigDecimal idRiesgo;
	private String descripcion;
	private Date fechaIngreso;
	private Date fechaActualizacion;
	private String usuarioIngreso;
	private String usuarioActualizacion;
	private String estado;

	public SairDocRiesgoDocumento() {
	}

	public SairDocRiesgoDocumento(BigDecimal idRiesgo, String descripcion,
			Date fechaIngreso, Date fechaActualizacion, String usuarioIngreso,
			String usuarioActualizacion, String estado) {
		this.idRiesgo = idRiesgo;
		this.descripcion = descripcion;
		this.fechaIngreso = fechaIngreso;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioIngreso = usuarioIngreso;
		this.usuarioActualizacion = usuarioActualizacion;
		this.estado = estado;
	}


	public BigDecimal getIdRiesgo() {
		return this.idRiesgo;
	}

	public void setIdRiesgo(BigDecimal idRiesgo) {
		this.idRiesgo = idRiesgo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
