package ec.com.rgt.sair.hbm;

import java.sql.Clob;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Lob;

/**
 * SairDocPlantillaDocumento generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocPlantillaDocumento implements java.io.Serializable {

	private SairDocPlantillaDocumentoId id;
	private SairDocTipoInforme sairDocTipoInforme;
	private SairDocTipoDocumento sairDocTipoDocumento;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String detalle;
	private String usuarioIngreso;
	private Date fechaIngreso;
	private Date ultimaModificacion;
	private String estado,reviso,propietario,plantillaEnvio;

	public SairDocPlantillaDocumento() {
	}

	public SairDocPlantillaDocumento(SairDocPlantillaDocumentoId id,
			SairDocTipoInforme sairDocTipoInforme,
			SairDocTipoDocumento sairDocTipoDocumento,
			SairDocReservacionCodigo sairDocReservacionCodigo, String detalle,
			String usuarioIngreso, Date fechaIngreso, Date ultimaModificacion,
			String estado,String reviso,String propietario,String plantillaEnvio) {
		this.id = id;
		this.sairDocTipoInforme = sairDocTipoInforme;
		this.sairDocTipoDocumento = sairDocTipoDocumento;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.detalle = detalle;
		this.usuarioIngreso = usuarioIngreso;
		this.fechaIngreso = fechaIngreso;
		this.ultimaModificacion = ultimaModificacion;
		this.estado = estado;
		this.reviso = reviso;
		this.propietario = propietario;
		this.plantillaEnvio = plantillaEnvio;
	}

	
	public String getPlantillaEnvio() {
		return plantillaEnvio;
	}

	public void setPlantillaEnvio(String plantillaEnvio) {
		this.plantillaEnvio = plantillaEnvio;
	}

	public String getReviso() {
		return reviso;
	}

	public void setReviso(String reviso) {
		this.reviso = reviso;
	}

	public String getPropietario() {
		return propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	public SairDocPlantillaDocumentoId getId() {
		return this.id;
	}

	public void setId(SairDocPlantillaDocumentoId id) {
		this.id = id;
	}

	public SairDocTipoInforme getSairDocTipoInforme() {
		return this.sairDocTipoInforme;
	}

	public void setSairDocTipoInforme(SairDocTipoInforme sairDocTipoInforme) {
		this.sairDocTipoInforme = sairDocTipoInforme;
	}

	public SairDocTipoDocumento getSairDocTipoDocumento() {
		return this.sairDocTipoDocumento;
	}

	public void setSairDocTipoDocumento(
			SairDocTipoDocumento sairDocTipoDocumento) {
		this.sairDocTipoDocumento = sairDocTipoDocumento;
	}
	
	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getUltimaModificacion() {
		return this.ultimaModificacion;
	}

	public void setUltimaModificacion(Date ultimaModificacion) {
		this.ultimaModificacion = ultimaModificacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
