package ec.com.rgt.sair.hbm;

// Generated 18-feb-2015 14:36:19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocAntecedente generated by hbmjava
 */
public class SairDocAntecedente implements java.io.Serializable {

	private BigDecimal idAntecedente;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String antecedente;
	private Date fechaIngreso,fechaActualiza;
	private String estado;

	public SairDocAntecedente() {
	}
	
	public Date getFechaActualiza() {
		return fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public SairDocAntecedente(BigDecimal idAntecedente) {
		this.idAntecedente = idAntecedente;
	}

	public SairDocAntecedente(BigDecimal idAntecedente,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			String antecedente, Date fechaIngreso, String estado,Date fechaActualiza) {
		this.idAntecedente = idAntecedente;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.antecedente = antecedente;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.fechaActualiza = fechaActualiza;
	}

	public BigDecimal getIdAntecedente() {
		return this.idAntecedente;
	}

	public void setIdAntecedente(BigDecimal idAntecedente) {
		this.idAntecedente = idAntecedente;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getAntecedente() {
		return this.antecedente;
	}

	public void setAntecedente(String antecedente) {
		this.antecedente = antecedente;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
