package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairPersonalId generated by hbmjava
 */
public class SairPersonalId implements java.io.Serializable {

	private BigDecimal perId;
	private BigDecimal areaId;

	public SairPersonalId() {
	}

	public SairPersonalId(BigDecimal perId, BigDecimal areaId) {
		this.perId = perId;
		this.areaId = areaId;
	}

	public BigDecimal getPerId() {
		return this.perId;
	}

	public void setPerId(BigDecimal perId) {
		this.perId = perId;
	}

	public BigDecimal getAreaId() {
		return this.areaId;
	}

	public void setAreaId(BigDecimal areaId) {
		this.areaId = areaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairPersonalId))
			return false;
		SairPersonalId castOther = (SairPersonalId) other;

		return ((this.getPerId() == castOther.getPerId()) || (this.getPerId() != null
				&& castOther.getPerId() != null && this.getPerId().equals(
				castOther.getPerId())))
				&& ((this.getAreaId() == castOther.getAreaId()) || (this
						.getAreaId() != null && castOther.getAreaId() != null && this
						.getAreaId().equals(castOther.getAreaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPerId() == null ? 0 : this.getPerId().hashCode());
		result = 37 * result
				+ (getAreaId() == null ? 0 : this.getAreaId().hashCode());
		return result;
	}

}
