package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairIncSubtipo generated by hbmjava
 */
public class SairIncSubtipo implements java.io.Serializable {

	private BigDecimal idSubtipo;
	private SairIncIncidencia sairIncIncidencia;
	private SairIncTipo sairIncTipo;
	private String idUsuarioCreacion;
	private String nombre;
	private String descripcion;
	private Date fechaCreacion;
	private String estado;

	public SairIncSubtipo() {
	}

	public SairIncSubtipo(BigDecimal idSubtipo, SairIncTipo sairIncTipo,
			String estado) {
		this.idSubtipo = idSubtipo;
		this.sairIncTipo = sairIncTipo;
		this.estado = estado;
	}

	public SairIncSubtipo(BigDecimal idSubtipo,
			SairIncIncidencia sairIncIncidencia, SairIncTipo sairIncTipo,
			String idUsuarioCreacion, String nombre, String descripcion,
			Date fechaCreacion, String estado) {
		this.idSubtipo = idSubtipo;
		this.sairIncIncidencia = sairIncIncidencia;
		this.sairIncTipo = sairIncTipo;
		this.idUsuarioCreacion = idUsuarioCreacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
	}

	public BigDecimal getIdSubtipo() {
		return this.idSubtipo;
	}

	public void setIdSubtipo(BigDecimal idSubtipo) {
		this.idSubtipo = idSubtipo;
	}

	public SairIncIncidencia getSairIncIncidencia() {
		return this.sairIncIncidencia;
	}

	public void setSairIncIncidencia(SairIncIncidencia sairIncIncidencia) {
		this.sairIncIncidencia = sairIncIncidencia;
	}

	public SairIncTipo getSairIncTipo() {
		return this.sairIncTipo;
	}

	public void setSairIncTipo(SairIncTipo sairIncTipo) {
		this.sairIncTipo = sairIncTipo;
	}

	public String getIdUsuarioCreacion() {
		return this.idUsuarioCreacion;
	}

	public void setIdUsuarioCreacion(String idUsuarioCreacion) {
		this.idUsuarioCreacion = idUsuarioCreacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
