package ec.com.rgt.sair.hbm;

// Generated 10-ene-2014 11:48:23 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocPlantilla generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocPlantilla implements java.io.Serializable {

	private BigDecimal idPlantilla;
	private BigDecimal idPlantillaHijo;
	private String nombre;
	private String plantilla;
	private Date fechaIngreso;
	private String usuarioIngreso;
	private String estado;
	private SairParRutina sairParRutina;

	public SairDocPlantilla() {
	}

	public SairDocPlantilla(BigDecimal idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public SairDocPlantilla(BigDecimal idPlantilla,
			BigDecimal idPlantillaHijo, String nombre, String plantilla,
			Date fechaIngreso, String usuarioIngreso, String estado, SairParRutina sairParRutina) {
		this.idPlantilla = idPlantilla;
		this.idPlantillaHijo = idPlantillaHijo;
		this.nombre = nombre;
		this.plantilla = plantilla;
		this.fechaIngreso = fechaIngreso;
		this.usuarioIngreso = usuarioIngreso;
		this.estado = estado;
		this.sairParRutina=sairParRutina;
	}

	public BigDecimal getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(BigDecimal idPlantilla) {
		this.idPlantilla = idPlantilla;
	}


	public BigDecimal getIdPlantillaHijo() {
		return idPlantillaHijo;
	}

	public void setIdPlantillaHijo(BigDecimal idPlantillaHijo) {
		this.idPlantillaHijo = idPlantillaHijo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPlantilla() {
		return this.plantilla;
	}

	public void setPlantilla(String plantilla) {
		this.plantilla = plantilla;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}
}
