package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairEstadosPrincipal generated by hbmjava
 */
public class SairEstadosPrincipal implements java.io.Serializable {

	private BigDecimal idEstado;
	private String indice;
	private String descripcion;
	private Date fechaIngreso;
	private String usuarioIngreso;
	private String estado;


	public SairEstadosPrincipal() {
	}

	public SairEstadosPrincipal(BigDecimal idEstado, String indice,
			String descripcion, Date fechaIngreso, String usuarioIngreso) {
		this.idEstado = idEstado;
		this.indice = indice;
		this.descripcion = descripcion;
		this.fechaIngreso = fechaIngreso;
		this.usuarioIngreso = usuarioIngreso;
		this.estado = estado;
	}


	public BigDecimal getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(BigDecimal idEstado) {
		this.idEstado = idEstado;
	}

	public String getIndice() {
		return this.indice;
	}

	public void setIndice(String indice) {
		this.indice = indice;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}
	
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
