package ec.com.rgt.sair.hbm;
// Generated 17/01/2017 14:24:19 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;


/**
 * SairActaProyecto generated by hbm2java
 */
//@XmlTransient
public class SairActaProyecto implements java.io.Serializable {

	private BigDecimal idProyecto;
	private SairActaTipos sairActaTipos;
	private SairActaTipo sairActaTipo;
	private SairActaEstatus sairActaEstatus;
	private Date fechaApertura;
	private String solicitante;
	private String nombre;
	private String objetivo;
	private String idResponsable;
	private Date fechaObjectivo;
	private Date fechaRealFin,fechaSolicitudCierre;
	private BigDecimal idActaDependiente,num,idHito,idArea;
	private Date fechaIngreso;
	private String comentarioSolicitud;
	private String idUsuarioSolicitud;
	private Date fechaInicio;
    private String entregable;
	
	public SairActaProyecto() {
	}

	public SairActaProyecto(BigDecimal idProyecto) {
		this.idProyecto = idProyecto;
	}

	public SairActaProyecto(BigDecimal idProyecto, SairActaTipos sairActaTipos, SairActaTipo sairActaTipo,
			 SairActaEstatus sairActaEstatus, Date fechaApertura, String solicitante,
			String nombre, String objetivo, String idResponsable, Date fechaObjectivo, Date fechaRealFin,Date fechaSolicitudCierre,
			BigDecimal idActaDependiente, Date fechaIngreso, String comentarioSolicitud, String idUsuarioSolicitud,BigDecimal num,BigDecimal idHito,BigDecimal idArea) {
		this.idProyecto = idProyecto;
		this.sairActaTipos = sairActaTipos;
		this.sairActaTipo = sairActaTipo;
		this.idHito = idHito;
		this.sairActaEstatus = sairActaEstatus;
		this.fechaApertura = fechaApertura;
		this.solicitante = solicitante;
		this.nombre = nombre;
		this.objetivo = objetivo;
		this.idResponsable = idResponsable;
		this.fechaObjectivo = fechaObjectivo;
		this.fechaRealFin = fechaRealFin;
		this.idActaDependiente = idActaDependiente;
		this.fechaIngreso = fechaIngreso;
		this.comentarioSolicitud = comentarioSolicitud;
		this.idUsuarioSolicitud = idUsuarioSolicitud;
		this.num = num;
		this.idArea = idArea;
		this.fechaSolicitudCierre = fechaSolicitudCierre;
	}


	public SairActaProyecto(BigDecimal idProyecto, SairActaTipos sairActaTipos, SairActaTipo sairActaTipo,
			 SairActaEstatus sairActaEstatus, Date fechaApertura, String solicitante,
			String nombre, String objetivo, String idResponsable, Date fechaObjectivo, Date fechaRealFin,Date fechaSolicitudCierre,
			BigDecimal idActaDependiente, Date fechaIngreso, String comentarioSolicitud, String idUsuarioSolicitud,BigDecimal num,BigDecimal idHito
			,BigDecimal idArea, String entregable) {
		this.idProyecto = idProyecto;
		this.sairActaTipos = sairActaTipos;
		this.sairActaTipo = sairActaTipo;
		this.idHito = idHito;
		this.sairActaEstatus = sairActaEstatus;
		this.fechaApertura = fechaApertura;
		this.solicitante = solicitante;
		this.nombre = nombre;
		this.objetivo = objetivo;
		this.idResponsable = idResponsable;
		this.fechaObjectivo = fechaObjectivo;
		this.fechaRealFin = fechaRealFin;
		this.idActaDependiente = idActaDependiente;
		this.fechaIngreso = fechaIngreso;
		this.comentarioSolicitud = comentarioSolicitud;
		this.idUsuarioSolicitud = idUsuarioSolicitud;
		this.num = num;
		this.idArea = idArea;
		this.fechaSolicitudCierre = fechaSolicitudCierre;
		this.entregable = entregable;
	}


	public SairActaProyecto(BigDecimal idProyecto, SairActaTipos sairActaTipos, SairActaTipo sairActaTipo,
			 SairActaEstatus sairActaEstatus, Date fechaApertura, String solicitante,
			String nombre, String objetivo, String idResponsable, Date fechaObjectivo, Date fechaRealFin,Date fechaSolicitudCierre,
			BigDecimal idActaDependiente, Date fechaIngreso, String comentarioSolicitud, String idUsuarioSolicitud,BigDecimal num,BigDecimal idHito
			,BigDecimal idArea, Date fechaInicio, String entregable) {
		this.idProyecto = idProyecto;
		this.sairActaTipos = sairActaTipos;
		this.sairActaTipo = sairActaTipo;
		this.idHito = idHito;
		this.sairActaEstatus = sairActaEstatus;
		this.fechaApertura = fechaApertura;
		this.solicitante = solicitante;
		this.nombre = nombre;
		this.objetivo = objetivo;
		this.idResponsable = idResponsable;
		this.fechaObjectivo = fechaObjectivo;
		this.fechaRealFin = fechaRealFin;
		this.idActaDependiente = idActaDependiente;
		this.fechaIngreso = fechaIngreso;
		this.comentarioSolicitud = comentarioSolicitud;
		this.idUsuarioSolicitud = idUsuarioSolicitud;
		this.num = num;
		this.idArea = idArea;
		this.fechaSolicitudCierre = fechaSolicitudCierre;
		this.fechaInicio = fechaInicio;
		this.entregable = entregable;
	}
	
	public BigDecimal getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(BigDecimal idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Date getFechaSolicitudCierre() {
		return fechaSolicitudCierre;
	}

	public void setFechaSolicitudCierre(Date fechaSolicitudCierre) {
		this.fechaSolicitudCierre = fechaSolicitudCierre;
	}

	public BigDecimal getIdArea() {
		return idArea;
	}

	public void setIdArea(BigDecimal idArea) {
		this.idArea = idArea;
	}

	public BigDecimal getIdHito() {
		return idHito;
	}

	public void setIdHito(BigDecimal idHito) {
		this.idHito = idHito;
	}

	public SairActaTipos getSairActaTipos() {
		return this.sairActaTipos;
	}

	public void setSairActaTipos(SairActaTipos sairActaTipos) {
		this.sairActaTipos = sairActaTipos;
	}

	public SairActaTipo getSairActaTipo() {
		return this.sairActaTipo;
	}

	public void setSairActaTipo(SairActaTipo sairActaTipo) {
		this.sairActaTipo = sairActaTipo;
	}

	public SairActaEstatus getSairActaEstatus() {
		return this.sairActaEstatus;
	}

	public void setSairActaEstatus(SairActaEstatus sairActaEstatus) {
		this.sairActaEstatus = sairActaEstatus;
	}

	public Date getFechaApertura() {
		return this.fechaApertura;
	}

	public void setFechaApertura(Date fechaApertura) {
		this.fechaApertura = fechaApertura;
	}

	public String getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(String solicitante) {
		this.solicitante = solicitante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	public String getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(String idResponsable) {
		this.idResponsable = idResponsable;
	}

	public Date getFechaObjectivo() {
		return this.fechaObjectivo;
	}

	public void setFechaObjectivo(Date fechaObjectivo) {
		this.fechaObjectivo = fechaObjectivo;
	}

	public Date getFechaRealFin() {
		return this.fechaRealFin;
	}

	public void setFechaRealFin(Date fechaRealFin) {
		this.fechaRealFin = fechaRealFin;
	}

	public BigDecimal getIdActaDependiente() {
		return this.idActaDependiente;
	}

	public void setIdActaDependiente(BigDecimal idActaDependiente) {
		this.idActaDependiente = idActaDependiente;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getComentarioSolicitud() {
		return this.comentarioSolicitud;
	}

	public void setComentarioSolicitud(String comentarioSolicitud) {
		this.comentarioSolicitud = comentarioSolicitud;
	}

	public String getIdUsuarioSolicitud() {
		return this.idUsuarioSolicitud;
	}

	public void setIdUsuarioSolicitud(String idUsuarioSolicitud) {
		this.idUsuarioSolicitud = idUsuarioSolicitud;
	}

	public BigDecimal getNum() {
		return num;
	}

	public void setNum(BigDecimal num) {
		this.num = num;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public String getEntregable() {
		return entregable;
	}

	public void setEntregable(String entregable) {
		this.entregable = entregable;
	}
	
	

}
