package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairParProgramaRutina generated by hbmjava
 */
public class SairParProgramaRutina implements java.io.Serializable {

	private BigDecimal idProgramaRutina;
	private SairParRutina sairParRutina;
	private BigDecimal anio;
	private BigDecimal mes;
	private BigDecimal semana1;
	private BigDecimal semana2;
	private BigDecimal semana3;
	private BigDecimal semana4;
	private String estado;
	private BigDecimal idPeriodicidad;

	public SairParProgramaRutina() {
	}

	public SairParProgramaRutina(BigDecimal idProgramaRutina,
			SairParRutina sairParRutina, BigDecimal anio, String estado) {
		this.idProgramaRutina = idProgramaRutina;
		this.sairParRutina = sairParRutina;
		this.anio = anio;
		this.estado = estado;
	}

	public SairParProgramaRutina(BigDecimal idProgramaRutina,
			SairParRutina sairParRutina, BigDecimal anio, BigDecimal mes,
			BigDecimal semana1, BigDecimal semana2, BigDecimal semana3,
			BigDecimal semana4, String estado, BigDecimal idPeriodicidad) {
		this.idProgramaRutina = idProgramaRutina;
		this.sairParRutina = sairParRutina;
		this.anio = anio;
		this.mes = mes;
		this.semana1 = semana1;
		this.semana2 = semana2;
		this.semana3 = semana3;
		this.semana4 = semana4;
		this.estado = estado;
		this.idPeriodicidad = idPeriodicidad;
	}

	public BigDecimal getIdProgramaRutina() {
		return this.idProgramaRutina;
	}

	public void setIdProgramaRutina(BigDecimal idProgramaRutina) {
		this.idProgramaRutina = idProgramaRutina;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}

	public BigDecimal getAnio() {
		return this.anio;
	}

	public void setAnio(BigDecimal anio) {
		this.anio = anio;
	}

	public BigDecimal getMes() {
		return this.mes;
	}

	public void setMes(BigDecimal mes) {
		this.mes = mes;
	}

	public BigDecimal getSemana1() {
		return this.semana1;
	}

	public void setSemana1(BigDecimal semana1) {
		this.semana1 = semana1;
	}

	public BigDecimal getSemana2() {
		return this.semana2;
	}

	public void setSemana2(BigDecimal semana2) {
		this.semana2 = semana2;
	}

	public BigDecimal getSemana3() {
		return this.semana3;
	}

	public void setSemana3(BigDecimal semana3) {
		this.semana3 = semana3;
	}

	public BigDecimal getSemana4() {
		return this.semana4;
	}

	public void setSemana4(BigDecimal semana4) {
		this.semana4 = semana4;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	public BigDecimal getIdPeriodicidad() {
		return this.idPeriodicidad;
	}

	public void setIdPeriodicidad(BigDecimal idPeriodicidad) {
		this.idPeriodicidad = idPeriodicidad;
	}
	
}