package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocPlantillaDocumentoId generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocPlantillaDocumentoId implements java.io.Serializable {

	private BigDecimal idPlantillaDocuemtno;
	private BigDecimal idTipoDocumento;

	public SairDocPlantillaDocumentoId() {
	}

	public SairDocPlantillaDocumentoId(BigDecimal idPlantillaDocuemtno,
			BigDecimal idTipoDocumento) {
		this.idPlantillaDocuemtno = idPlantillaDocuemtno;
		this.idTipoDocumento = idTipoDocumento;
	}

	public BigDecimal getIdPlantillaDocuemtno() {
		return this.idPlantillaDocuemtno;
	}

	public void setIdPlantillaDocuemtno(BigDecimal idPlantillaDocuemtno) {
		this.idPlantillaDocuemtno = idPlantillaDocuemtno;
	}

	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairDocPlantillaDocumentoId))
			return false;
		SairDocPlantillaDocumentoId castOther = (SairDocPlantillaDocumentoId) other;

		return ((this.getIdPlantillaDocuemtno() == castOther
				.getIdPlantillaDocuemtno()) || (this.getIdPlantillaDocuemtno() != null
				&& castOther.getIdPlantillaDocuemtno() != null && this
				.getIdPlantillaDocuemtno().equals(
						castOther.getIdPlantillaDocuemtno())))
				&& ((this.getIdTipoDocumento() == castOther
						.getIdTipoDocumento()) || (this.getIdTipoDocumento() != null
						&& castOther.getIdTipoDocumento() != null && this
						.getIdTipoDocumento().equals(
								castOther.getIdTipoDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdPlantillaDocuemtno() == null ? 0 : this
						.getIdPlantillaDocuemtno().hashCode());
		result = 37
				* result
				+ (getIdTipoDocumento() == null ? 0 : this.getIdTipoDocumento()
						.hashCode());
		return result;
	}

}
