package ec.com.rgt.sair.hbm;

// Generated 18-feb-2015 14:36:19 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocAlcance generated by hbmjava
 */
public class SairDocAlcance implements java.io.Serializable {

	private BigDecimal idAlcance;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String alcance;
	private Date fechaIngreso,fechaActualiza;
	private String estado;

	public SairDocAlcance() {
	}
	
	public Date getFechaActualiza() {
		return fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public SairDocAlcance(BigDecimal idAlcance) {
		this.idAlcance = idAlcance;
	}

	public SairDocAlcance(BigDecimal idAlcance,
			SairDocReservacionCodigo sairDocReservacionCodigo, String alcance,
			Date fechaIngreso, String estado,Date fechaActualiza) {
		this.idAlcance = idAlcance;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.alcance = alcance;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.fechaActualiza = fechaActualiza;
	}

	public BigDecimal getIdAlcance() {
		return this.idAlcance;
	}

	public void setIdAlcance(BigDecimal idAlcance) {
		this.idAlcance = idAlcance;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getAlcance() {
		return this.alcance;
	}

	public void setAlcance(String alcance) {
		this.alcance = alcance;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
