package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import ec.com.rgt.sair.hbm.SairRecRecomendacion;

/**
 * SairDocEscalamientoDocument generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocEscalamientoDocument implements java.io.Serializable {

	private BigDecimal idEscalamientoDocumento;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairRecRecomendacion sairRecRecomendacion;
	private String idUsuarioAic;
	private String idUsuarioAnterior;
	private Date fechaEscalamiento;
	private String estado,tipoUsuario;

	public SairDocEscalamientoDocument() {
	}

	public SairDocEscalamientoDocument(BigDecimal idEscalamientoDocumento,
			SairDocReservacionCodigo sairDocReservacionCodigo,SairRecRecomendacion sairRecRecomendacion, 
			String idUsuarioAic, String idUsuarioAnterior,
			Date fechaEscalamiento, String tipoUsuario) {
		this.idEscalamientoDocumento = idEscalamientoDocumento;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairRecRecomendacion = sairRecRecomendacion;
		this.idUsuarioAic = idUsuarioAic;
		this.idUsuarioAnterior = idUsuarioAnterior;
		this.fechaEscalamiento = fechaEscalamiento;
		this.tipoUsuario = tipoUsuario;
	}
	
	

	public String getTipoUsuario() {
		return tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public SairRecRecomendacion getSairRecRecomendacion() {
		return sairRecRecomendacion;
	}

	public void setSairRecRecomendacion(SairRecRecomendacion sairRecRecomendacion) {
		this.sairRecRecomendacion = sairRecRecomendacion;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getIdEscalamientoDocumento() {
		return this.idEscalamientoDocumento;
	}

	public void setIdEscalamientoDocumento(BigDecimal idEscalamientoDocumento) {
		this.idEscalamientoDocumento = idEscalamientoDocumento;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getIdUsuarioAic() {
		return this.idUsuarioAic;
	}

	public void setIdUsuarioAic(String idUsuarioAic) {
		this.idUsuarioAic = idUsuarioAic;
	}

	public String getIdUsuarioAnterior() {
		return this.idUsuarioAnterior;
	}

	public void setIdUsuarioAnterior(String idUsuarioAnterior) {
		this.idUsuarioAnterior = idUsuarioAnterior;
	}

	public Date getFechaEscalamiento() {
		return this.fechaEscalamiento;
	}

	public void setFechaEscalamiento(Date fechaEscalamiento) {
		this.fechaEscalamiento = fechaEscalamiento;
	}

}
