package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairRecEscalamiento generated by hbmjava
 */
public class SairRecEscalamiento implements java.io.Serializable {

	private BigDecimal idEscalReco;
	private SairRecRecomendacion sairRecRecomendacion;
	private String idUsuario;
	private String usuarioAnterior;
	private Date fechaEscalamiento;

	public SairRecEscalamiento() {
	}

	public SairRecEscalamiento(BigDecimal idEscalReco,
			SairRecRecomendacion sairRecRecomendacion, String usuarioAnterior,
			Date fechaEscalamiento) {
		this.idEscalReco = idEscalReco;
		this.sairRecRecomendacion = sairRecRecomendacion;
		this.usuarioAnterior = usuarioAnterior;
		this.fechaEscalamiento = fechaEscalamiento;
	}

	public SairRecEscalamiento(BigDecimal idEscalReco,
			SairRecRecomendacion sairRecRecomendacion, String idUsuario,
			String usuarioAnterior, Date fechaEscalamiento) {
		this.idEscalReco = idEscalReco;
		this.sairRecRecomendacion = sairRecRecomendacion;
		this.idUsuario = idUsuario;
		this.usuarioAnterior = usuarioAnterior;
		this.fechaEscalamiento = fechaEscalamiento;
	}

	public BigDecimal getIdEscalReco() {
		return this.idEscalReco;
	}

	public void setIdEscalReco(BigDecimal idEscalReco) {
		this.idEscalReco = idEscalReco;
	}

	public SairRecRecomendacion getSairRecRecomendacion() {
		return this.sairRecRecomendacion;
	}

	public void setSairRecRecomendacion(
			SairRecRecomendacion sairRecRecomendacion) {
		this.sairRecRecomendacion = sairRecRecomendacion;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getUsuarioAnterior() {
		return this.usuarioAnterior;
	}

	public void setUsuarioAnterior(String usuarioAnterior) {
		this.usuarioAnterior = usuarioAnterior;
	}

	public Date getFechaEscalamiento() {
		return this.fechaEscalamiento;
	}

	public void setFechaEscalamiento(Date fechaEscalamiento) {
		this.fechaEscalamiento = fechaEscalamiento;
	}

}
