package ec.com.rgt.sair.hbm;

// Generated 24-ago-2015 9:51:38 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairForumTag generated by hbmjava
 */
public class SairForumTag implements java.io.Serializable {

	private BigDecimal idTag;
	private String nombre;
	private String descripcion;
	private Date fechaIngreso;
	private String estado;
	private Set sairForumQuestionses = new HashSet(0);

	public SairForumTag() {
	}

	public SairForumTag(BigDecimal idTag) {
		this.idTag = idTag;
	}

	public SairForumTag(BigDecimal idTag, String nombre, String descripcion,
			Date fechaIngreso, String estado, Set sairForumQuestionses) {
		this.idTag = idTag;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.sairForumQuestionses = sairForumQuestionses;
	}

	public BigDecimal getIdTag() {
		return this.idTag;
	}

	public void setIdTag(BigDecimal idTag) {
		this.idTag = idTag;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairForumQuestionses() {
		return this.sairForumQuestionses;
	}

	public void setSairForumQuestionses(Set sairForumQuestionses) {
		this.sairForumQuestionses = sairForumQuestionses;
	}

}
