package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairDocTipoDocumento generated by hbmjava
 */
public class SairDocTipoDocumento implements java.io.Serializable {

	private BigDecimal idTipoDocumento;
	private String descripcion;
	private Date fechaIngreso;
	private String estado,prioridad;

	public SairDocTipoDocumento() {
	}

	public SairDocTipoDocumento(BigDecimal idTipoDocumento, String descripcion,
			Date fechaIngreso,String estado,String prioridad) {
		this.idTipoDocumento = idTipoDocumento;
		this.descripcion = descripcion;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.prioridad =prioridad;
	}


	public String getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(BigDecimal idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
