package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import ec.com.rgt.sair.hbm.SairEstadosPrincipal;
import ec.com.rgt.sair.hbm.SairRecRecomendacion;

/**
 * SairRecDependencia generated by hbmjava
 */
public class SairRecDependencia implements java.io.Serializable {

	private BigDecimal idSecuencial;
	private SairRecRecomendacion sairRecRecomendacionByIdRecomendacion;
	private SairEstadosPrincipal sairEstadosPrincipal;
	private SairRecRecomendacion sairRecRecomendacionByIdRecoDependiente;

	public SairRecDependencia() {
	}

	public SairRecDependencia(BigDecimal idSecuencial,
			SairRecRecomendacion sairRecRecomendacionByIdRecomendacion,
			SairEstadosPrincipal sairEstadosPrincipal,
			SairRecRecomendacion sairRecRecomendacionByIdRecoDependiente) {
		this.idSecuencial = idSecuencial;
		this.sairRecRecomendacionByIdRecomendacion = sairRecRecomendacionByIdRecomendacion;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
		this.sairRecRecomendacionByIdRecoDependiente = sairRecRecomendacionByIdRecoDependiente;
	}

	public BigDecimal getIdSecuencial() {
		return this.idSecuencial;
	}

	public void setIdSecuencial(BigDecimal idSecuencial) {
		this.idSecuencial = idSecuencial;
	}


	public SairRecRecomendacion getSairRecRecomendacionByIdRecomendacion() {
		return sairRecRecomendacionByIdRecomendacion;
	}

	public void setSairRecRecomendacionByIdRecomendacion(
			SairRecRecomendacion sairRecRecomendacionByIdRecomendacion) {
		this.sairRecRecomendacionByIdRecomendacion = sairRecRecomendacionByIdRecomendacion;
	}

	public SairRecRecomendacion getSairRecRecomendacionByIdRecoDependiente() {
		return sairRecRecomendacionByIdRecoDependiente;
	}

	public void setSairRecRecomendacionByIdRecoDependiente(
			SairRecRecomendacion sairRecRecomendacionByIdRecoDependiente) {
		this.sairRecRecomendacionByIdRecoDependiente = sairRecRecomendacionByIdRecoDependiente;
	}

	public SairEstadosPrincipal getSairEstadosPrincipal() {
		return this.sairEstadosPrincipal;
	}

	public void setSairEstadosPrincipal(
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	

}
