package ec.com.rgt.sair.hbm;

// Generated 01/12/2016 12:38:36 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairBriAccionAreaId generated by hbmjava
 */
public class SairBriAccionAreaId implements java.io.Serializable {

	private BigDecimal idAccion;
	private BigDecimal idDepartamento;

	public SairBriAccionAreaId() {
	}

	public SairBriAccionAreaId(BigDecimal idAccion, BigDecimal idDepartamento) {
		this.idAccion = idAccion;
		this.idDepartamento = idDepartamento;
	}

	public BigDecimal getIdAccion() {
		return this.idAccion;
	}

	public void setIdAccion(BigDecimal idAccion) {
		this.idAccion = idAccion;
	}

	public BigDecimal getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(BigDecimal idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairBriAccionAreaId))
			return false;
		SairBriAccionAreaId castOther = (SairBriAccionAreaId) other;

		return ((this.getIdAccion() == castOther.getIdAccion()) || (this
				.getIdAccion() != null && castOther.getIdAccion() != null && this
				.getIdAccion().equals(castOther.getIdAccion())))
				&& ((this.getIdDepartamento() == castOther.getIdDepartamento()) || (this
						.getIdDepartamento() != null
						&& castOther.getIdDepartamento() != null && this
						.getIdDepartamento().equals(
								castOther.getIdDepartamento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdAccion() == null ? 0 : this.getIdAccion().hashCode());
		result = 37
				* result
				+ (getIdDepartamento() == null ? 0 : this.getIdDepartamento()
						.hashCode());
		return result;
	}

}
