package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import ec.com.rgt.sair.hbm.SairDocAjusteCorreccion;

/**
 * SairDocInformes generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocInformes implements java.io.Serializable {

	private BigDecimal idInforme,p,i,casosSinAfectacion;
	private SairDocTipoInforme sairDocTipoInforme;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairDocInformes sairDocInformes;
	private SairEstadosPrincipal sairEstadosPrincipal;
	private SairDocRiesgoDocumento sairDocRiesgoDocumento;
	private String asunto;
	private String antecedente;
	private String alcance;
	private String comentario;
	private String prioridad;
	private BigDecimal codInforme;
	private Date fechaElaboracion;
	private Date fechaEmision;
	private String imagen;
	private BigDecimal cantidadRecomendaciones;
	private BigDecimal cantidadCasosRecuperar;
	private String errorOperativoTecnologico,errorTecnologico;
	private BigDecimal valorRecuperar;
	private BigDecimal valorDevolver;
	private BigDecimal cantidadCasosDevolver;
	private String revisadoSupervisor;
	private String revisadoJefe;
	private BigDecimal idEstadoComp;
	private BigDecimal codigo;
	private String estado;
	private BigDecimal idArea;
	private String ultimo;
	private SairDocAjusteCorreccion sairDocAjusteCorreccion;
	private String prioridadAjuste;
	private Date fechaEmisionReal;
	private String confidencial;


	
	public BigDecimal getCasosSinAfectacion() {
		return casosSinAfectacion;
	}

	public void setCasosSinAfectacion(BigDecimal casosSinAfectacion) {
		this.casosSinAfectacion = casosSinAfectacion;
	}

	public String getErrorTecnologico() {
		return errorTecnologico;
	}

	public void setErrorTecnologico(String errorTecnologico) {
		this.errorTecnologico = errorTecnologico;
	}

	public SairDocRiesgoDocumento getSairDocRiesgoDocumento() {
		return sairDocRiesgoDocumento;
	}

	public void setSairDocRiesgoDocumento(
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

	public SairDocAjusteCorreccion getSairDocAjusteCorreccion() {
		return sairDocAjusteCorreccion;
	}

	public void setSairDocAjusteCorreccion(
			SairDocAjusteCorreccion sairDocAjusteCorreccion) {
		this.sairDocAjusteCorreccion = sairDocAjusteCorreccion;
	}

	public String getPrioridadAjuste() {
		return prioridadAjuste;
	}

	public void setPrioridadAjuste(String prioridadAjuste) {
		this.prioridadAjuste = prioridadAjuste;
	}

	public String getUltimo() {
		return ultimo;
	}

	public void setUltimo(String ultimo) {
		this.ultimo = ultimo;
	}

	public SairDocInformes() {
	}

	public SairDocInformes(BigDecimal idInforme,
			SairDocTipoInforme sairDocTipoInforme,
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.idInforme = idInforme;
		this.sairDocTipoInforme = sairDocTipoInforme;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	public SairDocInformes(BigDecimal idInforme,
			BigDecimal codInforme,
			SairDocTipoInforme sairDocTipoInforme,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairDocInformes sairDocInformes,
			SairEstadosPrincipal sairEstadosPrincipal,
			SairDocAjusteCorreccion sairDocAjusteCorreccion, 
			SairDocRiesgoDocumento sairDocRiesgoDocumento,String asunto,
			String antecedente, String alcance, String comentario, String prioridad,
			Date fechaElaboracion, Date fechaEmision, String imagen,
			BigDecimal cantidadRecomendaciones,
			BigDecimal cantidadCasosRecuperar,
			String errorOperativoTecnologico, BigDecimal valorRecuperar,
			BigDecimal valorDevolver, BigDecimal cantidadCasosDevolver,
			String revisadoSupervisor, String revisadoJefe,
			BigDecimal idEstadoComp, BigDecimal codigo,String estado, 
			BigDecimal idArea,String ultimo,String prioridadAjuste,BigDecimal p,BigDecimal i,
			BigDecimal casosSinAfectacion,String errorTecnologico, Date fechaEmisionReal, String confidencial) {
		this.idInforme = idInforme;
		this.sairDocTipoInforme = sairDocTipoInforme;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairDocInformes = sairDocInformes;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
		this.asunto = asunto;
		this.antecedente = antecedente;
		this.alcance = alcance;
		this.comentario = comentario;
		this.prioridad = prioridad;
		this.fechaElaboracion = fechaElaboracion;
		this.fechaEmision = fechaEmision;
		this.imagen = imagen;
		this.cantidadRecomendaciones = cantidadRecomendaciones;
		this.cantidadCasosRecuperar = cantidadCasosRecuperar;
		this.errorOperativoTecnologico = errorOperativoTecnologico;
		this.valorRecuperar = valorRecuperar;
		this.valorDevolver = valorDevolver;
		this.cantidadCasosDevolver = cantidadCasosDevolver;
		this.revisadoSupervisor = revisadoSupervisor;
		this.revisadoJefe = revisadoJefe;
		this.idEstadoComp = idEstadoComp;
		this.codigo = codigo;
		this.estado = estado;
		this.idArea = idArea;
		this.codInforme = codInforme;
		this.ultimo = ultimo;
		this.sairDocRiesgoDocumento=sairDocRiesgoDocumento;
		this.prioridadAjuste = prioridadAjuste;
		this.p= p;
		this.i= i;
		this.casosSinAfectacion = casosSinAfectacion;
		this.errorTecnologico = errorTecnologico;
		this.fechaEmisionReal = fechaEmisionReal;
		this.confidencial = confidencial;
	}
	
	public BigDecimal getP() {
		return p;
	}

	public void setP(BigDecimal p) {
		this.p = p;
	}

	public BigDecimal getI() {
		return i;
	}
	
	public String getConfidencial() {
		return confidencial;
	}
	
	public void setConfidencial(String confidencial) {
		this.confidencial = confidencial;
	}

	public Date getFechaEmisionReal() {
		return fechaEmisionReal;
	}

	public void setFechaEmisionReal(Date fechaEmisionReal) {
		this.fechaEmisionReal = fechaEmisionReal;
	}

	public void setI(BigDecimal i) {
		this.i = i;
	}

	public BigDecimal getCodInforme() {
		return codInforme;
	}

	public void setCodInforme(BigDecimal codInforme) {
		this.codInforme = codInforme;
	}
	
	public BigDecimal getIdInforme() {
		return this.idInforme;
	}

	public void setIdInforme(BigDecimal idInforme) {
		this.idInforme = idInforme;
	}

	public SairDocTipoInforme getSairDocTipoInforme() {
		return this.sairDocTipoInforme;
	}

	public void setSairDocTipoInforme(SairDocTipoInforme sairDocTipoInforme) {
		this.sairDocTipoInforme = sairDocTipoInforme;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairDocInformes getSairDocInformes() {
		return this.sairDocInformes;
	}

	public void setSairDocInformes(SairDocInformes sairDocInformes) {
		this.sairDocInformes = sairDocInformes;
	}

	public SairEstadosPrincipal getSairEstadosPrincipal() {
		return this.sairEstadosPrincipal;
	}

	public void setSairEstadosPrincipal(
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getAntecedente() {
		return this.antecedente;
	}

	public void setAntecedente(String antecedente) {
		this.antecedente = antecedente;
	}

	public String getAlcance() {
		return this.alcance;
	}

	public void setAlcance(String alcance) {
		this.alcance = alcance;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public String getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public Date getFechaElaboracion() {
		return this.fechaElaboracion;
	}

	public void setFechaElaboracion(Date fechaElaboracion) {
		this.fechaElaboracion = fechaElaboracion;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public BigDecimal getCantidadRecomendaciones() {
		return this.cantidadRecomendaciones;
	}

	public void setCantidadRecomendaciones(BigDecimal cantidadRecomendaciones) {
		this.cantidadRecomendaciones = cantidadRecomendaciones;
	}

	public BigDecimal getCantidadCasosRecuperar() {
		return this.cantidadCasosRecuperar;
	}

	public void setCantidadCasosRecuperar(BigDecimal cantidadCasosRecuperar) {
		this.cantidadCasosRecuperar = cantidadCasosRecuperar;
	}

	public String getErrorOperativoTecnologico() {
		return this.errorOperativoTecnologico;
	}

	public void setErrorOperativoTecnologico(String errorOperativoTecnologico) {
		this.errorOperativoTecnologico = errorOperativoTecnologico;
	}

	public BigDecimal getValorRecuperar() {
		return this.valorRecuperar;
	}

	public void setValorRecuperar(BigDecimal valorRecuperar) {
		this.valorRecuperar = valorRecuperar;
	}

	public BigDecimal getValorDevolver() {
		return this.valorDevolver;
	}

	public void setValorDevolver(BigDecimal valorDevolver) {
		this.valorDevolver = valorDevolver;
	}

	public BigDecimal getCantidadCasosDevolver() {
		return this.cantidadCasosDevolver;
	}

	public void setCantidadCasosDevolver(BigDecimal cantidadCasosDevolver) {
		this.cantidadCasosDevolver = cantidadCasosDevolver;
	}

	public String getRevisadoSupervisor() {
		return this.revisadoSupervisor;
	}

	public void setRevisadoSupervisor(String revisadoSupervisor) {
		this.revisadoSupervisor = revisadoSupervisor;
	}

	public String getRevisadoJefe() {
		return this.revisadoJefe;
	}

	public void setRevisadoJefe(String revisadoJefe) {
		this.revisadoJefe = revisadoJefe;
	}

	public BigDecimal getIdEstadoComp() {
		return this.idEstadoComp;
	}

	public void setIdEstadoComp(BigDecimal idEstadoComp) {
		this.idEstadoComp = idEstadoComp;
	}

	public BigDecimal getCodigo() {
		return this.codigo;
	}

	public void setCodigo(BigDecimal codigo) {
		this.codigo = codigo;
	}
	
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	public BigDecimal getIdArea() {
		return this.idArea;
	}

	public void setIdArea(BigDecimal idArea) {
		this.idArea = idArea;
	}
}
