package ec.com.rgt.sair.hbm;

// Generated 15/11/2016 11:03:39 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriProgramacion generated by hbmjava
 */
public class SairBriProgramacion implements java.io.Serializable {

	private BigDecimal idProgramacion;
	private SairBriSolicitud sairBriSolicitud;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairBriEstados sairBriEstados;
	private String idUsuario;
	private Date fechaSalida,fechaResp;
	private BigDecimal idRutina;
	private String idUsuarioRecibe,respuesta,codigo;
	private Set sairBriBriefs = new HashSet(0);

	public SairBriProgramacion() {
	}

	public SairBriProgramacion(BigDecimal idProgramacion) {
		this.idProgramacion = idProgramacion;
	}

	public SairBriProgramacion(BigDecimal idProgramacion,
			SairBriSolicitud sairBriSolicitud,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairBriEstados sairBriEstados, String idUsuario, Date fechaSalida,
			BigDecimal idRutina, String idUsuarioRecibe,String respuesta,Date fechaResp, String codigo, Set sairBriBriefs) {
		this.idProgramacion = idProgramacion;
		this.sairBriSolicitud = sairBriSolicitud;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairBriEstados = sairBriEstados;
		this.idUsuario = idUsuario;
		this.fechaSalida = fechaSalida;
		this.idRutina = idRutina;
		this.idUsuarioRecibe = idUsuarioRecibe;
		this.sairBriBriefs = sairBriBriefs;
		this.fechaResp =fechaResp;
		this.respuesta = respuesta;
		this.codigo=codigo;
	}

	public BigDecimal getIdProgramacion() {
		return this.idProgramacion;
	}

	public void setIdProgramacion(BigDecimal idProgramacion) {
		this.idProgramacion = idProgramacion;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Date getFechaResp() {
		return fechaResp;
	}

	public void setFechaResp(Date fechaResp) {
		this.fechaResp = fechaResp;
	}

	public String getRespuesta() {
		return respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public SairBriSolicitud getSairBriSolicitud() {
		return this.sairBriSolicitud;
	}

	public void setSairBriSolicitud(SairBriSolicitud sairBriSolicitud) {
		this.sairBriSolicitud = sairBriSolicitud;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairBriEstados getSairBriEstados() {
		return this.sairBriEstados;
	}

	public void setSairBriEstados(SairBriEstados sairBriEstados) {
		this.sairBriEstados = sairBriEstados;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	public BigDecimal getIdRutina() {
		return this.idRutina;
	}

	public void setIdRutina(BigDecimal idRutina) {
		this.idRutina = idRutina;
	}

	public String getIdUsuarioRecibe() {
		return this.idUsuarioRecibe;
	}

	public void setIdUsuarioRecibe(String idUsuarioRecibe) {
		this.idUsuarioRecibe = idUsuarioRecibe;
	}

	public Set getSairBriBriefs() {
		return this.sairBriBriefs;
	}

	public void setSairBriBriefs(Set sairBriBriefs) {
		this.sairBriBriefs = sairBriBriefs;
	}

}
