package ec.com.rgt.sair.hbm;

// Generated 18-sep-2014 11:45:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairIncTipo generated by hbmjava
 */
public class SairIncTipo implements java.io.Serializable {

	private BigDecimal idTipo;
	private String idUsuarioCreacion;
	private String nombre;
	private Date fechaCreacion;
	private String estado;
	private String codigo;
	private BigDecimal tipo;
	private Set sairObservacioneses = new HashSet(0);
	private Set sairIncIncidencias = new HashSet(0);
	private Set sairIncSubtipos = new HashSet(0);

	public SairIncTipo() {
	}

	public SairIncTipo(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public SairIncTipo(BigDecimal idTipo, String idUsuarioCreacion,
			String nombre, Date fechaCreacion, String estado, String codigo,
			BigDecimal tipo, Set sairObservacioneses, Set sairIncIncidencias,
			Set sairIncSubtipos) {
		this.idTipo = idTipo;
		this.idUsuarioCreacion = idUsuarioCreacion;
		this.nombre = nombre;
		this.fechaCreacion = fechaCreacion;
		this.estado = estado;
		this.codigo = codigo;
		this.tipo = tipo;
		this.sairObservacioneses = sairObservacioneses;
		this.sairIncIncidencias = sairIncIncidencias;
		this.sairIncSubtipos = sairIncSubtipos;
	}

	public BigDecimal getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(BigDecimal idTipo) {
		this.idTipo = idTipo;
	}

	public String getIdUsuarioCreacion() {
		return this.idUsuarioCreacion;
	}

	public void setIdUsuarioCreacion(String idUsuarioCreacion) {
		this.idUsuarioCreacion = idUsuarioCreacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public BigDecimal getTipo() {
		return this.tipo;
	}

	public void setTipo(BigDecimal tipo) {
		this.tipo = tipo;
	}

	public Set getSairObservacioneses() {
		return this.sairObservacioneses;
	}

	public void setSairObservacioneses(Set sairObservacioneses) {
		this.sairObservacioneses = sairObservacioneses;
	}

	public Set getSairIncIncidencias() {
		return this.sairIncIncidencias;
	}

	public void setSairIncIncidencias(Set sairIncIncidencias) {
		this.sairIncIncidencias = sairIncIncidencias;
	}

	public Set getSairIncSubtipos() {
		return this.sairIncSubtipos;
	}

	public void setSairIncSubtipos(Set sairIncSubtipos) {
		this.sairIncSubtipos = sairIncSubtipos;
	}

}
