package ec.com.rgt.sair.hbm;

// Generated 02-jul-2014 10:33:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import ec.com.rgt.sair.controller.ClobAdapter;

/**
 * SairPlantillas generated by hbmjava
 */
@XmlRootElement
public class SairPlantillas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idPlantilla;
	private String nombre;
	private Clob descripcion;
	private String estado;

	public SairPlantillas() {
	}

	public SairPlantillas(BigDecimal idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public SairPlantillas(BigDecimal idPlantilla, String nombre,
			Clob descripcion, String estado) {
		this.idPlantilla = idPlantilla;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public BigDecimal getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(BigDecimal idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@XmlJavaTypeAdapter(ClobAdapter.class)
	public Clob getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Clob descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
