package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairObsAccionAdm generated by hbmjava
 */
public class SairObsTipoJustificacion implements java.io.Serializable {

	private BigDecimal idTipoJustificacion;
	private String nombre;
	private String estado;

	public SairObsTipoJustificacion() {
	}

	public SairObsTipoJustificacion(BigDecimal idTipoJustificacion, String nombre,String estado) {
		this.idTipoJustificacion = idTipoJustificacion;
		this.nombre = nombre;
		this.estado=estado;
	}

	public BigDecimal getIdTipoJustificacion() {
		return idTipoJustificacion;
	}

	public void setIdTipoJustificacion(BigDecimal idTipoJustificacion) {
		this.idTipoJustificacion = idTipoJustificacion;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
