package ec.com.rgt.sair.hbm;

// Generated 30-jun-2014 12:03:18 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocEscalamiento generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocEscalamiento implements java.io.Serializable {

	private BigDecimal idEscalamiento;
	private SairDocTipoDocumento sairDocTipoDocumento;
	private BigDecimal dias;
	private Date fechaIngreso;
	private Date fechaActualiza;
	private String estado;

	public SairDocEscalamiento() {
	}

	public SairDocEscalamiento(BigDecimal idEscalamiento) {
		this.idEscalamiento = idEscalamiento;
	}

	public SairDocEscalamiento(BigDecimal idEscalamiento,
			SairDocTipoDocumento sairDocTipoDocumento, BigDecimal dias,
			Date fechaIngreso, Date fechaActualiza, String estado) {
		this.idEscalamiento = idEscalamiento;
		this.sairDocTipoDocumento = sairDocTipoDocumento;
		this.dias = dias;
		this.fechaIngreso = fechaIngreso;
		this.fechaActualiza = fechaActualiza;
		this.estado = estado;
	}

	public BigDecimal getIdEscalamiento() {
		return this.idEscalamiento;
	}

	public void setIdEscalamiento(BigDecimal idEscalamiento) {
		this.idEscalamiento = idEscalamiento;
	}

	public SairDocTipoDocumento getSairDocTipoDocumento() {
		return this.sairDocTipoDocumento;
	}

	public void setSairDocTipoDocumento(
			SairDocTipoDocumento sairDocTipoDocumento) {
		this.sairDocTipoDocumento = sairDocTipoDocumento;
	}

	public BigDecimal getDias() {
		return this.dias;
	}

	public void setDias(BigDecimal dias) {
		this.dias = dias;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
