package ec.com.rgt.sair.hbm;
// Generated 13/01/2017 15:02:53 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairActaComentario generated by hbm2java
 */
public class SairActaComentario implements java.io.Serializable {

	private BigDecimal idComentario;
	private SairActaProyecto sairActaProyecto;
	private String idUsuario;
	private Date fechaIngreso;
	private String url;
	private String ext;
	private String comentario;

	public SairActaComentario() {
	}

	public SairActaComentario(BigDecimal idComentario) {
		this.idComentario = idComentario;
	}

	public SairActaComentario(BigDecimal idComentario, SairActaProyecto sairActaProyecto, String idUsuario,
			Date fechaIngreso, String url, String ext, String comentario) {
		this.idComentario = idComentario;
		this.sairActaProyecto = sairActaProyecto;
		this.idUsuario = idUsuario;
		this.fechaIngreso = fechaIngreso;
		this.url = url;
		this.ext = ext;
		this.comentario = comentario;
	}

	public BigDecimal getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(BigDecimal idComentario) {
		this.idComentario = idComentario;
	}

	public SairActaProyecto getSairActaProyecto() {
		return this.sairActaProyecto;
	}

	public void setSairActaProyecto(SairActaProyecto sairActaProyecto) {
		this.sairActaProyecto = sairActaProyecto;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
