package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

/**
 * SairPersonal generated by hbmjava
 */
public class SairPersonal implements java.io.Serializable {

	private SairPersonalId id;
	private String perNombre;
	private String perCargo;
	private String perEstado;
	private String perCorreo;

	public SairPersonal() {
	}

	public SairPersonal(SairPersonalId id, String perNombre, String perCargo,
			String perEstado, String perCorreo) {
		this.id = id;
		this.perNombre = perNombre;
		this.perCargo = perCargo;
		this.perEstado = perEstado;
		this.perCorreo = perCorreo;
	}

	public SairPersonalId getId() {
		return this.id;
	}

	public void setId(SairPersonalId id) {
		this.id = id;
	}

	public String getPerNombre() {
		return this.perNombre;
	}

	public void setPerNombre(String perNombre) {
		this.perNombre = perNombre;
	}

	public String getPerCargo() {
		return this.perCargo;
	}

	public void setPerCargo(String perCargo) {
		this.perCargo = perCargo;
	}

	public String getPerEstado() {
		return this.perEstado;
	}

	public void setPerEstado(String perEstado) {
		this.perEstado = perEstado;
	}

	public String getPerCorreo() {
		return this.perCorreo;
	}

	public void setPerCorreo(String perCorreo) {
		this.perCorreo = perCorreo;
	}

}
