package ec.com.rgt.sair.hbm;

// Generated 20-mar-2015 9:48:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairDocAjusteCorreccion generated by hbmjava
 */
public class SairDocAjusteCorreccion implements java.io.Serializable {

	private BigDecimal idAjuste;
	private String nombre;
	private Date fechaIngreso;
	private String estado;
	private String prioridad;
	private Set sairDocInformeses = new HashSet(0);

	
	
	public String getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(String prioridad) {
		this.prioridad = prioridad;
	}

	public SairDocAjusteCorreccion() {
	}

	public SairDocAjusteCorreccion(BigDecimal idAjuste) {
		this.idAjuste = idAjuste;
	}

	public SairDocAjusteCorreccion(BigDecimal idAjuste, String nombre,
			Date fechaIngreso, String estado,String prioridad,Set sairDocInformeses) {
		this.idAjuste = idAjuste;
		this.nombre = nombre;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.sairDocInformeses = sairDocInformeses;
		this.prioridad=prioridad;
	}

	public BigDecimal getIdAjuste() {
		return this.idAjuste;
	}

	public void setIdAjuste(BigDecimal idAjuste) {
		this.idAjuste = idAjuste;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairDocInformeses() {
		return this.sairDocInformeses;
	}

	public void setSairDocInformeses(Set sairDocInformeses) {
		this.sairDocInformeses = sairDocInformeses;
	}

}
