package ec.com.rgt.sair.hbm;

// Generated 07-feb-2014 15:13:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocPasos generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocPasos implements java.io.Serializable {

	private BigDecimal idPasos;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String idUsuario;
	private Date fechaIngreso,fechaActualiza;
	private String estado;
	private String pasos;

	public SairDocPasos() {
	}
	
	public Date getFechaActualiza() {
		return fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public SairDocPasos(BigDecimal idPasos) {
		this.idPasos = idPasos;
	}

	public SairDocPasos(BigDecimal idPasos,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			String idUsuario, Date fechaIngreso, String estado, String pasos,Date fechaActualiza) {
		this.idPasos = idPasos;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.idUsuario = idUsuario;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.pasos = pasos;
		this.fechaActualiza = fechaActualiza;
	}

	public BigDecimal getIdPasos() {
		return this.idPasos;
	}

	public void setIdPasos(BigDecimal idPasos) {
		this.idPasos = idPasos;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getPasos() {
		return this.pasos;
	}

	public void setPasos(String pasos) {
		this.pasos = pasos;
	}

}
