package ec.com.rgt.sair.hbm;
// Generated 13/01/2017 15:02:53 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairActaEstatus generated by hbm2java
 */
public class SairActaEstatus implements java.io.Serializable {

	private BigDecimal idEstatus;
	private String nobre;
	private String estado;
	private Set sairActaProyectos = new HashSet(0);

	public SairActaEstatus() {
	}

	public SairActaEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

	public SairActaEstatus(BigDecimal idEstatus, String nobre, String estado, Set sairActaProyectos) {
		this.idEstatus = idEstatus;
		this.nobre = nobre;
		this.estado = estado;
		this.sairActaProyectos = sairActaProyectos;
	}

	public BigDecimal getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

	public String getNobre() {
		return this.nobre;
	}

	public void setNobre(String nobre) {
		this.nobre = nobre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairActaProyectos() {
		return this.sairActaProyectos;
	}

	public void setSairActaProyectos(Set sairActaProyectos) {
		this.sairActaProyectos = sairActaProyectos;
	}

}
