package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairEstadoComplementario generated by hbmjava
 */
public class SairEstadoComplementario implements java.io.Serializable {

	private BigDecimal idEstado;
	private String nombre;
	private String descripcion;
	private String estado;
	private SairEstadoReco sairEstadoReco;

	public SairEstadoReco getSairEstadoReco() {
		return sairEstadoReco;
	}

	public void setSairEstadoReco(SairEstadoReco sairEstadoReco) {
		this.sairEstadoReco = sairEstadoReco;
	}

	public SairEstadoComplementario() {
	}

	public SairEstadoComplementario(BigDecimal idEstado) {
		this.idEstado = idEstado;
	}

	public SairEstadoComplementario(BigDecimal idEstado, String nombre,
			String descripcion, String estado,SairEstadoReco sairEstadoReco) {
		this.idEstado = idEstado;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.sairEstadoReco = sairEstadoReco;
	}

	public BigDecimal getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(BigDecimal idEstado) {
		this.idEstado = idEstado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
