package ec.com.rgt.sair.hbm;

// Generated 30-ene-2014 12:38:25 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocDiscusionInf generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocDiscusionInf implements java.io.Serializable {

	private BigDecimal idDiscusion;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String idUsuario;
	private Date fechaIngreso;
	private String estado;
	private String discusion;
	private String url;
	private String extencion;
	

	public SairDocDiscusionInf() {
	}

	public SairDocDiscusionInf(BigDecimal idDiscusion,
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.idDiscusion = idDiscusion;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public SairDocDiscusionInf(BigDecimal idDiscusion,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			String idUsuario, Date fechaIngreso, String estado, String discusion,String url,String extencion) {
		this.idDiscusion = idDiscusion;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.idUsuario = idUsuario;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.discusion = discusion;
		this.url = url;
		this.extencion = extencion;
	}

	
	
	public String getExtencion() {
		return extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	
	public BigDecimal getIdDiscusion() {
		return this.idDiscusion;
	}

	public void setIdDiscusion(BigDecimal idDiscusion) {
		this.idDiscusion = idDiscusion;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getDiscusion() {
		return this.discusion;
	}

	public void setDiscusion(String discusion) {
		this.discusion = discusion;
	}

}
