package ec.com.rgt.sair.hbm;

// Generated 02-oct-2014 10:17:55 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocImpacto generated by hbmjava
 */
public class SairDocImpacto implements java.io.Serializable {

	private BigDecimal idImpacto;
	private String nombre;
	private String estado;

	public SairDocImpacto() {
	}

	public SairDocImpacto(BigDecimal idImpacto) {
		this.idImpacto = idImpacto;
	}

	public SairDocImpacto(BigDecimal idImpacto, String nombre, String estado) {
		this.idImpacto = idImpacto;
		this.nombre = nombre;
		this.estado = estado;
	}

	public BigDecimal getIdImpacto() {
		return this.idImpacto;
	}

	public void setIdImpacto(BigDecimal idImpacto) {
		this.idImpacto = idImpacto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
