package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairObsDetallesFaltas generated by hbmjava
 */
public class SairObsDetallesFaltas implements java.io.Serializable {

	private BigDecimal idDetalleFaltas;
	private String descripcion;
	private String estado;

	public SairObsDetallesFaltas() {
	}

	public SairObsDetallesFaltas(BigDecimal idDetalleFaltas,
			String descripcion, String estado) {
		this.idDetalleFaltas = idDetalleFaltas;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public BigDecimal getIdDetalleFaltas() {
		return this.idDetalleFaltas;
	}

	public void setIdDetalleFaltas(BigDecimal idDetalleFaltas) {
		this.idDetalleFaltas = idDetalleFaltas;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
