package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * SairParCheckList generated by hbmjava
 */

public class SairParCheckList implements java.io.Serializable {

	private BigDecimal checkList;
	private SairParRutina sairParRutina;
	private SairParCheckListCabecera sairParCheckListCabecera;
	private String nombre;
	private String descripcion;
	private Date fecha;
	private BigDecimal codigo;
	private BigDecimal orden;
	private String estado;

	public SairParCheckList() {
	}

	public SairParCheckList(BigDecimal checkList) {
		this.checkList = checkList;
	}

	public SairParCheckList(BigDecimal checkList, SairParRutina sairParRutina,
			SairParCheckListCabecera sairParCheckListCabecera, String nombre,
			String descripcion, Date fecha, BigDecimal codigo,
			BigDecimal orden) {
		this.checkList = checkList;
		this.sairParRutina = sairParRutina;
		this.sairParCheckListCabecera = sairParCheckListCabecera;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.codigo = codigo;
		this.orden = orden;
		this.estado = estado;

	}

	public BigDecimal getCheckList() {
		return this.checkList;
	}

	public void setCheckList(BigDecimal checkList) {
		this.checkList = checkList;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}

	public SairParCheckListCabecera getSairParCheckListCabecera() {
		return this.sairParCheckListCabecera;
	}

	public void setSairParCheckListCabecera(
			SairParCheckListCabecera sairParCheckListCabecera) {
		this.sairParCheckListCabecera = sairParCheckListCabecera;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public BigDecimal getCodigo() {
		return this.codigo;
	}

	public void setCodigo(BigDecimal codigo) {
		this.codigo = codigo;
	}

	public BigDecimal getOrden() {
		return this.orden;
	}

	public void setOrden(BigDecimal orden) {
		this.orden = orden;
	}
	
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
