package ec.com.rgt.sair.hbm;

// Generated 01/12/2016 12:38:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * SairBriAccionArea generated by hbmjava
 */
public class SairBriAccionArea implements java.io.Serializable {

	private SairBriAccionAreaId id;
	private SairAreasAdam sairAreasAdam;
	private SairBriAcciones sairBriAcciones;
	private String estado;

	public SairBriAccionArea() {
	}

	public SairBriAccionArea(SairBriAccionAreaId id,
			SairAreasAdam sairAreasAdam, SairBriAcciones sairBriAcciones) {
		this.id = id;
		this.sairAreasAdam = sairAreasAdam;
		this.sairBriAcciones = sairBriAcciones;
	}

	public SairBriAccionArea(SairBriAccionAreaId id,
			SairAreasAdam sairAreasAdam, SairBriAcciones sairBriAcciones,
			String estado) {
		this.id = id;
		this.sairAreasAdam = sairAreasAdam;
		this.sairBriAcciones = sairBriAcciones;
		this.estado = estado;
	}

	public SairBriAccionAreaId getId() {
		return this.id;
	}

	public void setId(SairBriAccionAreaId id) {
		this.id = id;
	}

	public SairAreasAdam getSairAreasAdam() {
		return this.sairAreasAdam;
	}

	public void setSairAreasAdam(SairAreasAdam sairAreasAdam) {
		this.sairAreasAdam = sairAreasAdam;
	}

	public SairBriAcciones getSairBriAcciones() {
		return this.sairBriAcciones;
	}

	public void setSairBriAcciones(SairBriAcciones sairBriAcciones) {
		this.sairBriAcciones = sairBriAcciones;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
