package ec.com.rgt.sair.hbm;

// Generated 18-jul-2014 14:23:05 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairSubArea generated by hbmjava
 */
public class SairSubArea implements java.io.Serializable {

	private BigDecimal idArea;
	private String descripcion;
	private BigDecimal idDepartamento;
	private String codiAdam;
	private String estado,idGerente;
	private String subAreaPrincipal;

	public SairSubArea() {
	}

	public SairSubArea(BigDecimal idArea) {
		this.idArea = idArea;
	}

	public SairSubArea(BigDecimal idArea, String descripcion,
			BigDecimal idDepartamento, String codiAdam, String estado,String idGerente, String subAreaPrincipal) {
		this.idArea = idArea;
		this.descripcion = descripcion;
		this.idDepartamento = idDepartamento;
		this.codiAdam = codiAdam;
		this.estado = estado;
		this.idGerente = idGerente;
		this.subAreaPrincipal = subAreaPrincipal;
	}

	
	public String getIdGerente() {
		return idGerente;
	}

	public void setIdGerente(String idGerente) {
		this.idGerente = idGerente;
	}

	public BigDecimal getIdArea() {
		return this.idArea;
	}

	public void setIdArea(BigDecimal idArea) {
		this.idArea = idArea;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public BigDecimal getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(BigDecimal idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	public String getCodiAdam() {
		return this.codiAdam;
	}

	public void setCodiAdam(String codiAdam) {
		this.codiAdam = codiAdam;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getSubAreaPrincipal() {
		return subAreaPrincipal;
	}

	public void setSubAreaPrincipal(String subAreaPrincipal) {
		this.subAreaPrincipal = subAreaPrincipal;
	}
	
	
}
