package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairNotificacion generated by hbmjava
 */
public class SairNotificacion implements java.io.Serializable {

	private BigDecimal idNotificacion;
	private Date fecha;
	private String descripcion;
	private String tipo;
	private String usuarioCreacion;
	private String modulo;
	private String estado;
	private String usuarioDir;
	private BigDecimal idDoc;
	private BigDecimal idTipoDoc;

	public SairNotificacion() {
	}

	public SairNotificacion(BigDecimal idNotificacion, Date fecha,
			String descripcion, String tipo, String usuarioCreacion,
			String modulo, String estado, String usuarioDir,BigDecimal idDoc, BigDecimal idTipoDoc) {
		this.idNotificacion = idNotificacion;
		this.fecha = fecha;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.usuarioCreacion = usuarioCreacion;
		this.modulo = modulo;
		this.estado = estado;
		this.usuarioDir = usuarioDir;
		this.idDoc = idDoc;
		this.idTipoDoc = idTipoDoc;
	}

	public BigDecimal getIdTipoDoc() {
		return idTipoDoc;
	}

	public void setIdTipoDoc(BigDecimal idTipoDoc) {
		this.idTipoDoc = idTipoDoc;
	}

	public BigDecimal getIdDoc() {
		return idDoc;
	}

	public void setIdDoc(BigDecimal idDoc) {
		this.idDoc = idDoc;
	}

	public String getUsuarioDir() {
		return usuarioDir;
	}

	public void setUsuarioDir(String usuarioDir) {
		this.usuarioDir = usuarioDir;
	}

	public BigDecimal getIdNotificacion() {
		return this.idNotificacion;
	}

	public void setIdNotificacion(BigDecimal idNotificacion) {
		this.idNotificacion = idNotificacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
