package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1


/**
 * SairObsAccionAdm generated by hbmjava
 */
public class SairObsLocalidad implements java.io.Serializable {

	private String idLocalidad;
	private String nombre,direccion,jefe,nombreReal;
	private String estado;

	public SairObsLocalidad() {
	}

	
	public SairObsLocalidad(String idLocalidad, String nombre,
			String direccion, String jefe, String estado,String nombreReal) {
		super();
		this.idLocalidad = idLocalidad;
		this.nombre = nombre;
		this.direccion = direccion;
		this.jefe = jefe;
		this.estado = estado;
		this.nombreReal = nombreReal;
	}
	
	public String getNombreReal() {
		return nombreReal;
	}


	public void setNombreReal(String nombreReal) {
		this.nombreReal = nombreReal;
	}


	public String getIdLocalidad() {
		return idLocalidad;
	}


	public void setIdLocalidad(String idLocalidad) {
		this.idLocalidad = idLocalidad;
	}


	public String getNombre() {
		return nombre;
	}


	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	public String getDireccion() {
		return direccion;
	}


	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}


	public String getJefe() {
		return jefe;
	}


	public void setJefe(String jefe) {
		this.jefe = jefe;
	}


	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
