package ec.com.rgt.sair.hbm;

// Generated 14/11/2016 03:24:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriEstatus generated by hbmjava
 */
public class SairBriEstatus implements java.io.Serializable {

	private BigDecimal idEstatus;
	private String nombre;
	private String estado;

	public SairBriEstatus() {
	}

	public SairBriEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

	public SairBriEstatus(BigDecimal idEstatus, String nombre, String estado) {
		this.idEstatus = idEstatus;
		this.nombre = nombre;
		this.estado = estado;
	}

	public BigDecimal getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(BigDecimal idEstatus) {
		this.idEstatus = idEstatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}


}
