package ec.com.rgt.sair.hbm;

// Generated 08-may-2014 14:31:12 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairLog generated by hbmjava
 */
public class SairLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idLog;
	private SairTipoLog sairTipoLog;
	private String modulo;
	private String menu;
	private String metodo;
	private BigDecimal linea;
	private String usuario;
	private String ipUsuario;
	private String descripcion;
	private Date fechaIngreso;
	private String log;
	private String estado;

	public SairLog() {
	}

	public SairLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	public SairLog(BigDecimal idLog, SairTipoLog sairTipoLog, String modulo,
			String menu, String metodo, BigDecimal linea, String usuario,
			String ipUsuario, String descripcion, Date fechaIngreso, String log,
			String estado) {
		this.idLog = idLog;
		this.sairTipoLog = sairTipoLog;
		this.modulo = modulo;
		this.menu = menu;
		this.metodo = metodo;
		this.linea = linea;
		this.usuario = usuario;
		this.ipUsuario = ipUsuario;
		this.descripcion = descripcion;
		this.fechaIngreso = fechaIngreso;
		this.log = log;
		this.estado = estado;
	}

	public BigDecimal getIdLog() {
		return this.idLog;
	}

	public void setIdLog(BigDecimal idLog) {
		this.idLog = idLog;
	}

	public SairTipoLog getSairTipoLog() {
		return this.sairTipoLog;
	}

	public void setSairTipoLog(SairTipoLog sairTipoLog) {
		this.sairTipoLog = sairTipoLog;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getMenu() {
		return this.menu;
	}

	public void setMenu(String menu) {
		this.menu = menu;
	}

	public String getMetodo() {
		return this.metodo;
	}

	public void setMetodo(String metodo) {
		this.metodo = metodo;
	}

	public BigDecimal getLinea() {
		return this.linea;
	}

	public void setLinea(BigDecimal linea) {
		this.linea = linea;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getIpUsuario() {
		return this.ipUsuario;
	}

	public void setIpUsuario(String ipUsuario) {
		this.ipUsuario = ipUsuario;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
