package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairParComentarioRutina generated by hbmjava
 */
public class SairParComentarioRutina implements java.io.Serializable {

	private BigDecimal idComentario;
	private String observacion;
	private String estado;

	public SairParComentarioRutina() {
	}

	public SairParComentarioRutina(BigDecimal idComentario, String observacion,
			String estado) {
		this.idComentario = idComentario;
		this.observacion = observacion;
		this.estado = estado;
	}

	public BigDecimal getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(BigDecimal idComentario) {
		this.idComentario = idComentario;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
