package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairParProcedimientoAmx generated by hbmjava
 */
public class SairParProcedimientoAmx implements java.io.Serializable {

	private BigDecimal idProcedimientoAmx;
	private SairParRutina sairParRutina;
	private String iprocedimiento;

	public SairParProcedimientoAmx() {
	}

	public SairParProcedimientoAmx(BigDecimal idProcedimientoAmx,
			SairParRutina sairParRutina, String iprocedimiento) {
		this.idProcedimientoAmx = idProcedimientoAmx;
		this.sairParRutina = sairParRutina;
		this.iprocedimiento = iprocedimiento;
	}

	public BigDecimal getIdProcedimientoAmx() {
		return this.idProcedimientoAmx;
	}

	public void setIdProcedimientoAmx(BigDecimal idProcedimientoAmx) {
		this.idProcedimientoAmx = idProcedimientoAmx;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}

	public String getIprocedimiento() {
		return this.iprocedimiento;
	}

	public void setIprocedimiento(String iprocedimiento) {
		this.iprocedimiento = iprocedimiento;
	}

}
