package ec.com.rgt.sair.hbm;

// Generated 24/11/2016 10:47:18 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairBriAnexos generated by hbmjava
 */
public class SairBriAnexos implements java.io.Serializable {

	private BigDecimal idAnexo;
	private SairBriBrief sairBriBrief;
	private String nombre;
	private String ruta;
	private String ext;

	public SairBriAnexos() {
	}

	public SairBriAnexos(BigDecimal idAnexo) {
		this.idAnexo = idAnexo;
	}

	public SairBriAnexos(BigDecimal idAnexo, SairBriBrief sairBriBrief,
			String nombre, String ruta, String ext) {
		this.idAnexo = idAnexo;
		this.sairBriBrief = sairBriBrief;
		this.nombre = nombre;
		this.ruta = ruta;
		this.ext = ext;
	}

	public BigDecimal getIdAnexo() {
		return this.idAnexo;
	}

	public void setIdAnexo(BigDecimal idAnexo) {
		this.idAnexo = idAnexo;
	}

	public SairBriBrief getSairBriBrief() {
		return this.sairBriBrief;
	}

	public void setSairBriBrief(SairBriBrief sairBriBrief) {
		this.sairBriBrief = sairBriBrief;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

}
