package ec.com.rgt.sair.hbm;

// Generated 18-feb-2014 14:57:16 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairDocArnp generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairDocArnp implements java.io.Serializable {

	private BigDecimal idArnp;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private SairEstadoComplementario sairEstadoComplementario;
	private SairArea sairArea;
	private SairEstadosPrincipal sairEstadosPrincipal;
	private String asunto;
	private BigDecimal codArnp;
	private Date fechaEmision;
	private BigDecimal cantReco;
	private Date fechaIngreso;
	private String usuarioIngreso;
	private String estado;
	private String alcance;
	private String antecedentes;
	private String revisadoSupervisor;
	private String revisadoJefe;
	private String comentario;
	private Date fechaEmisionReal;

	public SairDocArnp() {
	}

	public SairDocArnp(BigDecimal idArnp) {
		this.idArnp = idArnp;
	}

	public SairDocArnp(BigDecimal idArnp,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			SairEstadoComplementario sairEstadoComplementario,
			SairArea sairArea, SairEstadosPrincipal sairEstadosPrincipal,
			String asunto, BigDecimal codArnp, Date fechaEmision,
			BigDecimal cantReco, Date fechaIngreso, String usuarioIngreso,
			String estado, String alcance, String antecedentes,
			String revisadoSupervisor, String revisadoJefe,String comentario, Date fechaEmisionReal) {
		this.idArnp = idArnp;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.sairEstadoComplementario = sairEstadoComplementario;
		this.sairArea = sairArea;
		this.sairEstadosPrincipal = sairEstadosPrincipal;
		this.asunto = asunto;
		this.codArnp = codArnp;
		this.fechaEmision = fechaEmision;
		this.cantReco = cantReco;
		this.fechaIngreso = fechaIngreso;
		this.usuarioIngreso = usuarioIngreso;
		this.estado = estado;
		this.alcance = alcance;
		this.antecedentes = antecedentes;
		this.revisadoSupervisor = revisadoSupervisor;
		this.revisadoJefe = revisadoJefe;
		this.comentario = comentario;
		this.fechaEmision = fechaEmisionReal;
	}

	public BigDecimal getIdArnp() {
		return this.idArnp;
	}

	public void setIdArnp(BigDecimal idArnp) {
		this.idArnp = idArnp;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public Date getFechaEmisionReal() {
		return fechaEmisionReal;
	}

	public void setFechaEmisionReal(Date fechaEmisionReal) {
		this.fechaEmisionReal = fechaEmisionReal;
	}

	public SairEstadoComplementario getSairEstadoComplementario() {
		return this.sairEstadoComplementario;
	}

	public void setSairEstadoComplementario(
			SairEstadoComplementario sairEstadoComplementario) {
		this.sairEstadoComplementario = sairEstadoComplementario;
	}

	public SairArea getSairArea() {
		return this.sairArea;
	}

	public void setSairArea(SairArea sairArea) {
		this.sairArea = sairArea;
	}

	public SairEstadosPrincipal getSairEstadosPrincipal() {
		return this.sairEstadosPrincipal;
	}

	public void setSairEstadosPrincipal(
			SairEstadosPrincipal sairEstadosPrincipal) {
		this.sairEstadosPrincipal = sairEstadosPrincipal;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public BigDecimal getCodArnp() {
		return this.codArnp;
	}

	public void setCodArnp(BigDecimal codArnp) {
		this.codArnp = codArnp;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public BigDecimal getCantReco() {
		return this.cantReco;
	}

	public void setCantReco(BigDecimal cantReco) {
		this.cantReco = cantReco;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getAlcance() {
		return this.alcance;
	}

	public void setAlcance(String alcance) {
		this.alcance = alcance;
	}

	public String getAntecedentes() {
		return this.antecedentes;
	}

	public void setAntecedentes(String antecedentes) {
		this.antecedentes = antecedentes;
	}

	public String getRevisadoSupervisor() {
		return this.revisadoSupervisor;
	}

	public void setRevisadoSupervisor(String revisadoSupervisor) {
		this.revisadoSupervisor = revisadoSupervisor;
	}

	public String getRevisadoJefe() {
		return this.revisadoJefe;
	}

	public void setRevisadoJefe(String revisadoJefe) {
		this.revisadoJefe = revisadoJefe;
	}
	
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
