package ec.com.rgt.sair.hbm;

// Generated 06-oct-2014 9:29:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SairDocConRiesgo generated by hbmjava
 */
public class SairDocConRiesgo implements java.io.Serializable {

	private BigDecimal idConRiesgo;
	private SairDocConclusionDocumento sairDocConclusionDocumento;
	private SairDocRiesgoDocumento sairDocRiesgoDocumento;

	public SairDocConRiesgo() {
	}

	public SairDocConRiesgo(BigDecimal idConRiesgo) {
		this.idConRiesgo = idConRiesgo;
	}

	public SairDocConRiesgo(BigDecimal idConRiesgo,
			SairDocConclusionDocumento sairDocConclusionDocumento,
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.idConRiesgo = idConRiesgo;
		this.sairDocConclusionDocumento = sairDocConclusionDocumento;
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

	public BigDecimal getIdConRiesgo() {
		return this.idConRiesgo;
	}

	public void setIdConRiesgo(BigDecimal idConRiesgo) {
		this.idConRiesgo = idConRiesgo;
	}

	public SairDocConclusionDocumento getSairDocConclusionDocumento() {
		return this.sairDocConclusionDocumento;
	}

	public void setSairDocConclusionDocumento(
			SairDocConclusionDocumento sairDocConclusionDocumento) {
		this.sairDocConclusionDocumento = sairDocConclusionDocumento;
	}

	public SairDocRiesgoDocumento getSairDocRiesgoDocumento() {
		return this.sairDocRiesgoDocumento;
	}

	public void setSairDocRiesgoDocumento(
			SairDocRiesgoDocumento sairDocRiesgoDocumento) {
		this.sairDocRiesgoDocumento = sairDocRiesgoDocumento;
	}

}
