package ec.com.rgt.sair.hbm;
// Generated 09/03/2017 14:16:09 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriBrief generated by hbm2java
 */
public class SairBriBrief implements java.io.Serializable {

	private BigDecimal idBrief,temp;
	private SairBriProgramacion sairBriProgramacion;
	private String codigo;
	private String idUsuario;
	private Date fechaCreacion;
	private Date fechaEmision;
	private String brief;
	private BigDecimal idArea;
	private Date fechaActualiza;
	private String estado;
	private String asunto;
	private String tema;
	private String escenario;
	private String agravante;
	private String riesgo;
	private Date fechaCierre;
	private Date fechaSolicitaCierre;
	private BigDecimal revision;
	private Date fechaResp;
	private String respuesta;
	private String desRiesgo;
	private String desImpacto;
	private String clientem;
	private String cuentam;
	private String equiposm;
	private String lineasm;
	private String otrosm;
	private String serviciosm;
	private String tarjetasm;
	private String UDevolverm;
	private String UNoPercibidom;
	private String URecuperarm;
	private String clientea;
	private String cuentaa;
	private String equiposa;
	private String lineasa;
	private String otrosa;
	private String serviciosa;
	private String tarjetasa;
	private String UDevolvera;
	private String UNoPercibidoa;
	private String URecuperara;
	private Set sairBriAccioneses = new HashSet(0);
	private Set sairBriAnexoses = new HashSet(0);

	public SairBriBrief() {
	}

	public SairBriBrief(BigDecimal idBrief) {
		this.idBrief = idBrief;
	}

	public SairBriBrief(BigDecimal idBrief, SairBriProgramacion sairBriProgramacion, String codigo, String idUsuario,
			Date fechaCreacion, Date fechaEmision, String brief, BigDecimal idArea, Date fechaActualiza, String estado,
			String asunto, String tema, String escenario, String agravante, String riesgo, Date fechaCierre,
			Date fechaSolicitaCierre, BigDecimal revision, Date fechaResp, String respuesta, String desRiesgo,
			String desImpacto, String clientem, String cuentam, String equiposm, String lineasm, String otrosm,
			String serviciosm, String tarjetasm, String UDevolverm, String UNoPercibidom, String URecuperarm,
			String clientea, String cuentaa, String equiposa, String lineasa, String otrosa, String serviciosa,
			String tarjetasa, String UDevolvera, String UNoPercibidoa, String URecuperara, BigDecimal temp,Set sairBriAccioneses,
			Set sairBriAnexoses) {
		this.idBrief = idBrief;
		this.sairBriProgramacion = sairBriProgramacion;
		this.codigo = codigo;
		this.idUsuario = idUsuario;
		this.fechaCreacion = fechaCreacion;
		this.fechaEmision = fechaEmision;
		this.brief = brief;
		this.idArea = idArea;
		this.fechaActualiza = fechaActualiza;
		this.estado = estado;
		this.asunto = asunto;
		this.tema = tema;
		this.escenario = escenario;
		this.agravante = agravante;
		this.riesgo = riesgo;
		this.fechaCierre = fechaCierre;
		this.fechaSolicitaCierre = fechaSolicitaCierre;
		this.revision = revision;
		this.fechaResp = fechaResp;
		this.respuesta = respuesta;
		this.desRiesgo = desRiesgo;
		this.desImpacto = desImpacto;
		this.clientem = clientem;
		this.cuentam = cuentam;
		this.equiposm = equiposm;
		this.lineasm = lineasm;
		this.otrosm = otrosm;
		this.serviciosm = serviciosm;
		this.tarjetasm = tarjetasm;
		this.UDevolverm = UDevolverm;
		this.UNoPercibidom = UNoPercibidom;
		this.URecuperarm = URecuperarm;
		this.clientea = clientea;
		this.cuentaa = cuentaa;
		this.equiposa = equiposa;
		this.lineasa = lineasa;
		this.otrosa = otrosa;
		this.serviciosa = serviciosa;
		this.tarjetasa = tarjetasa;
		this.UDevolvera = UDevolvera;
		this.UNoPercibidoa = UNoPercibidoa;
		this.URecuperara = URecuperara;
		this.temp =temp;
		this.sairBriAccioneses = sairBriAccioneses;
		this.sairBriAnexoses = sairBriAnexoses;
	}

	public BigDecimal getIdBrief() {
		return this.idBrief;
	}

	public void setIdBrief(BigDecimal idBrief) {
		this.idBrief = idBrief;
	}

	public BigDecimal getTemp() {
		return temp;
	}

	public void setTemp(BigDecimal temp) {
		this.temp = temp;
	}

	public SairBriProgramacion getSairBriProgramacion() {
		return this.sairBriProgramacion;
	}

	public void setSairBriProgramacion(SairBriProgramacion sairBriProgramacion) {
		this.sairBriProgramacion = sairBriProgramacion;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public String getBrief() {
		return this.brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}

	public BigDecimal getIdArea() {
		return this.idArea;
	}

	public void setIdArea(BigDecimal idArea) {
		this.idArea = idArea;
	}

	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getTema() {
		return this.tema;
	}

	public void setTema(String tema) {
		this.tema = tema;
	}

	public String getEscenario() {
		return this.escenario;
	}

	public void setEscenario(String escenario) {
		this.escenario = escenario;
	}

	public String getAgravante() {
		return this.agravante;
	}

	public void setAgravante(String agravante) {
		this.agravante = agravante;
	}

	public String getRiesgo() {
		return this.riesgo;
	}

	public void setRiesgo(String riesgo) {
		this.riesgo = riesgo;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Date getFechaSolicitaCierre() {
		return this.fechaSolicitaCierre;
	}

	public void setFechaSolicitaCierre(Date fechaSolicitaCierre) {
		this.fechaSolicitaCierre = fechaSolicitaCierre;
	}

	public BigDecimal getRevision() {
		return this.revision;
	}

	public void setRevision(BigDecimal revision) {
		this.revision = revision;
	}

	public Date getFechaResp() {
		return this.fechaResp;
	}

	public void setFechaResp(Date fechaResp) {
		this.fechaResp = fechaResp;
	}

	public String getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(String respuesta) {
		this.respuesta = respuesta;
	}

	public String getDesRiesgo() {
		return this.desRiesgo;
	}

	public void setDesRiesgo(String desRiesgo) {
		this.desRiesgo = desRiesgo;
	}

	public String getDesImpacto() {
		return this.desImpacto;
	}

	public void setDesImpacto(String desImpacto) {
		this.desImpacto = desImpacto;
	}

	public String getClientem() {
		return this.clientem;
	}

	public void setClientem(String clientem) {
		this.clientem = clientem;
	}

	public String getCuentam() {
		return this.cuentam;
	}

	public void setCuentam(String cuentam) {
		this.cuentam = cuentam;
	}

	public String getEquiposm() {
		return this.equiposm;
	}

	public void setEquiposm(String equiposm) {
		this.equiposm = equiposm;
	}

	public String getLineasm() {
		return this.lineasm;
	}

	public void setLineasm(String lineasm) {
		this.lineasm = lineasm;
	}

	public String getOtrosm() {
		return this.otrosm;
	}

	public void setOtrosm(String otrosm) {
		this.otrosm = otrosm;
	}

	public String getServiciosm() {
		return this.serviciosm;
	}

	public void setServiciosm(String serviciosm) {
		this.serviciosm = serviciosm;
	}

	public String getTarjetasm() {
		return this.tarjetasm;
	}

	public void setTarjetasm(String tarjetasm) {
		this.tarjetasm = tarjetasm;
	}

	public String getUDevolverm() {
		return this.UDevolverm;
	}

	public void setUDevolverm(String UDevolverm) {
		this.UDevolverm = UDevolverm;
	}

	public String getUNoPercibidom() {
		return this.UNoPercibidom;
	}

	public void setUNoPercibidom(String UNoPercibidom) {
		this.UNoPercibidom = UNoPercibidom;
	}

	public String getURecuperarm() {
		return this.URecuperarm;
	}

	public void setURecuperarm(String URecuperarm) {
		this.URecuperarm = URecuperarm;
	}

	public String getClientea() {
		return this.clientea;
	}

	public void setClientea(String clientea) {
		this.clientea = clientea;
	}

	public String getCuentaa() {
		return this.cuentaa;
	}

	public void setCuentaa(String cuentaa) {
		this.cuentaa = cuentaa;
	}

	public String getEquiposa() {
		return this.equiposa;
	}

	public void setEquiposa(String equiposa) {
		this.equiposa = equiposa;
	}

	public String getLineasa() {
		return this.lineasa;
	}

	public void setLineasa(String lineasa) {
		this.lineasa = lineasa;
	}

	public String getOtrosa() {
		return this.otrosa;
	}

	public void setOtrosa(String otrosa) {
		this.otrosa = otrosa;
	}

	public String getServiciosa() {
		return this.serviciosa;
	}

	public void setServiciosa(String serviciosa) {
		this.serviciosa = serviciosa;
	}

	public String getTarjetasa() {
		return this.tarjetasa;
	}

	public void setTarjetasa(String tarjetasa) {
		this.tarjetasa = tarjetasa;
	}

	public String getUDevolvera() {
		return this.UDevolvera;
	}

	public void setUDevolvera(String UDevolvera) {
		this.UDevolvera = UDevolvera;
	}

	public String getUNoPercibidoa() {
		return this.UNoPercibidoa;
	}

	public void setUNoPercibidoa(String UNoPercibidoa) {
		this.UNoPercibidoa = UNoPercibidoa;
	}

	public String getURecuperara() {
		return this.URecuperara;
	}

	public void setURecuperara(String URecuperara) {
		this.URecuperara = URecuperara;
	}

	public Set getSairBriAccioneses() {
		return this.sairBriAccioneses;
	}

	public void setSairBriAccioneses(Set sairBriAccioneses) {
		this.sairBriAccioneses = sairBriAccioneses;
	}

	public Set getSairBriAnexoses() {
		return this.sairBriAnexoses;
	}

	public void setSairBriAnexoses(Set sairBriAnexoses) {
		this.sairBriAnexoses = sairBriAnexoses;
	}

}
