package ec.com.rgt.sair.hbm;

// Generated 09-abr-2015 16:20:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairCalTipoEvento generated by hbmjava
 */
public class SairCalTipoEvento implements java.io.Serializable {

	private BigDecimal idTipoEvento;
	private String nombre;
	private String descripcion;
	private String colorCabecera;
	private String colorContenido;
	private Set sairCalEventoses = new HashSet(0);

	public SairCalTipoEvento() {
	}

	public SairCalTipoEvento(BigDecimal idTipoEvento, String nombre,
			String descripcion) {
		this.idTipoEvento = idTipoEvento;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public SairCalTipoEvento(BigDecimal idTipoEvento, String nombre,
			String descripcion, String colorCabecera, String colorContenido,
			Set sairCalEventoses) {
		this.idTipoEvento = idTipoEvento;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.colorCabecera = colorCabecera;
		this.colorContenido = colorContenido;
		this.sairCalEventoses = sairCalEventoses;
	}

	public BigDecimal getIdTipoEvento() {
		return this.idTipoEvento;
	}

	public void setIdTipoEvento(BigDecimal idTipoEvento) {
		this.idTipoEvento = idTipoEvento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getColorCabecera() {
		return this.colorCabecera;
	}

	public void setColorCabecera(String colorCabecera) {
		this.colorCabecera = colorCabecera;
	}

	public String getColorContenido() {
		return this.colorContenido;
	}

	public void setColorContenido(String colorContenido) {
		this.colorContenido = colorContenido;
	}

	public Set getSairCalEventoses() {
		return this.sairCalEventoses;
	}

	public void setSairCalEventoses(Set sairCalEventoses) {
		this.sairCalEventoses = sairCalEventoses;
	}

}
