package ec.com.rgt.sair.hbm;

// Generated 08-jul-2013 0:41:27 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GruposUsuariosId generated by hbmjava
 */
@SuppressWarnings("serial")
public class SairParUnidadRutinaId implements java.io.Serializable {

	private BigDecimal idSubArea,idRutina;

	public SairParUnidadRutinaId() {
	}


	public SairParUnidadRutinaId(BigDecimal idSubArea, BigDecimal idRutina) {
		super();
		this.idSubArea = idSubArea;
		this.idRutina = idRutina;
	}


	public BigDecimal getIdSubArea() {
		return idSubArea;
	}



	public void setIdSubArea(BigDecimal idSubArea) {
		this.idSubArea = idSubArea;
	}



	public BigDecimal getIdRutina() {
		return idRutina;
	}



	public void setIdRutina(BigDecimal idRutina) {
		this.idRutina = idRutina;
	}



	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SairParUnidadRutinaId))
			return false;
		SairParUnidadRutinaId castOther = (SairParUnidadRutinaId) other;

		return ((this.getIdSubArea() == castOther.getIdSubArea()) || (this
				.getIdSubArea() != null && castOther.getIdSubArea() != null && this
				.getIdSubArea().equals(castOther.getIdSubArea())))
				&& ((this.getIdRutina() == castOther.getIdRutina()) || (this
						.getIdRutina() != null && castOther.getIdRutina() != null && this
						.getIdRutina().equals(castOther.getIdRutina())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSubArea() == null ? 0 : this.getIdSubArea().hashCode());
		result = 37 * result
				+ (getIdRutina() == null ? 0 : this.getIdRutina().hashCode());
		return result;
	}

}
