package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairParDetalleCheckList generated by hbmjava
 */
public class SairParDetalleCheckList implements java.io.Serializable {

	private BigDecimal idDetalle;
	private SairParCheckList sairParCheckList;
	private BigDecimal orden;
	private String nombre;
	private String observaciones;
	private Date fecha;
	private String estado;

	public SairParDetalleCheckList() {
	}

	public SairParDetalleCheckList(BigDecimal idDetalle,
			SairParCheckList sairParCheckList, Date fecha) {
		this.idDetalle = idDetalle;
		this.sairParCheckList = sairParCheckList;
		this.fecha = fecha;
	}

	public SairParDetalleCheckList(BigDecimal idDetalle,
			SairParCheckList sairParCheckList, BigDecimal orden, String nombre,
			String observaciones,Date fecha) {
		this.idDetalle = idDetalle;
		this.sairParCheckList = sairParCheckList;
		this.orden = orden;
		this.nombre = nombre;
		this.observaciones = observaciones;
		this.fecha = fecha;
		this.estado = estado;
	}

	public BigDecimal getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(BigDecimal idDetalle) {
		this.idDetalle = idDetalle;
	}

	public SairParCheckList getSairParCheckList() {
		return this.sairParCheckList;
	}

	public void setSairParCheckList(SairParCheckList sairParCheckList) {
		this.sairParCheckList = sairParCheckList;
	}

	public BigDecimal getOrden() {
		return this.orden;
	}

	public void setOrden(BigDecimal orden) {
		this.orden = orden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
