package ec.com.rgt.sair.hbm;

// Generated 26-ene-2015 14:59:06 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairPoliticaProceso generated by hbmjava
 */
public class SairPoliticaProceso implements java.io.Serializable {

	private BigDecimal idProcesoAmx;
	private String nombre;
	private String estado;
	private Set sairPoliticaProcedimientos = new HashSet(0);

	public SairPoliticaProceso() {
	}

	public SairPoliticaProceso(BigDecimal idProcesoAmx) {
		this.idProcesoAmx = idProcesoAmx;
	}

	public SairPoliticaProceso(BigDecimal idProcesoAmx, String nombre,
			String estado, Set sairPoliticaProcedimientos) {
		this.idProcesoAmx = idProcesoAmx;
		this.nombre = nombre;
		this.estado = estado;
		this.sairPoliticaProcedimientos = sairPoliticaProcedimientos;
	}

	public BigDecimal getIdProcesoAmx() {
		return this.idProcesoAmx;
	}

	public void setIdProcesoAmx(BigDecimal idProcesoAmx) {
		this.idProcesoAmx = idProcesoAmx;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairPoliticaProcedimientos() {
		return this.sairPoliticaProcedimientos;
	}

	public void setSairPoliticaProcedimientos(Set sairPoliticaProcedimientos) {
		this.sairPoliticaProcedimientos = sairPoliticaProcedimientos;
	}

}
