package ec.com.rgt.sair.hbm;

// Generated 14-jul-2014 9:06:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairParDetalleRutina generated by hbmjava
 */
public class SairParDetalleRutina implements java.io.Serializable {

	private BigDecimal idDetalleRutina;
	private SairParRutina sairParRutina;
	private SairDocReservacionCodigo sairDocReservacionCodigo;
	private String idAsignado;
	private String idEjecutor;
	private Date fechaEjecucion;
	private String afirmaNiega;
	private BigDecimal semanaEmitido;
	private String justificado;
	private String estado;
	private String comentario;
	private BigDecimal anio;
	private BigDecimal mes;

	public SairParDetalleRutina() {
	}

	public SairParDetalleRutina(BigDecimal idDetalleRutina) {
		this.idDetalleRutina = idDetalleRutina;
	}

	public SairParDetalleRutina(BigDecimal idDetalleRutina,
			SairParRutina sairParRutina,
			SairDocReservacionCodigo sairDocReservacionCodigo,
			String idAsignado, String idEjecutor, Date fechaEjecucion,
			String afirmaNiega, BigDecimal semanaEmitido, String justificado,
			String estado, String comentario, BigDecimal anio, BigDecimal mes) {
		this.idDetalleRutina = idDetalleRutina;
		this.sairParRutina = sairParRutina;
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
		this.idAsignado = idAsignado;
		this.idEjecutor = idEjecutor;
		this.fechaEjecucion = fechaEjecucion;
		this.afirmaNiega = afirmaNiega;
		this.semanaEmitido = semanaEmitido;
		this.justificado = justificado;
		this.estado = estado;
		this.comentario = comentario;
		this.anio = anio;
		this.mes = mes;
	}

	public BigDecimal getIdDetalleRutina() {
		return this.idDetalleRutina;
	}

	public void setIdDetalleRutina(BigDecimal idDetalleRutina) {
		this.idDetalleRutina = idDetalleRutina;
	}

	public SairParRutina getSairParRutina() {
		return this.sairParRutina;
	}

	public void setSairParRutina(SairParRutina sairParRutina) {
		this.sairParRutina = sairParRutina;
	}

	public SairDocReservacionCodigo getSairDocReservacionCodigo() {
		return this.sairDocReservacionCodigo;
	}

	public void setSairDocReservacionCodigo(
			SairDocReservacionCodigo sairDocReservacionCodigo) {
		this.sairDocReservacionCodigo = sairDocReservacionCodigo;
	}

	public String getIdAsignado() {
		return this.idAsignado;
	}

	public void setIdAsignado(String idAsignado) {
		this.idAsignado = idAsignado;
	}

	public String getIdEjecutor() {
		return this.idEjecutor;
	}

	public void setIdEjecutor(String idEjecutor) {
		this.idEjecutor = idEjecutor;
	}

	public Date getFechaEjecucion() {
		return this.fechaEjecucion;
	}

	public void setFechaEjecucion(Date fechaEjecucion) {
		this.fechaEjecucion = fechaEjecucion;
	}

	public String getAfirmaNiega() {
		return this.afirmaNiega;
	}

	public void setAfirmaNiega(String afirmaNiega) {
		this.afirmaNiega = afirmaNiega;
	}

	public BigDecimal getSemanaEmitido() {
		return this.semanaEmitido;
	}

	public void setSemanaEmitido(BigDecimal semanaEmitido) {
		this.semanaEmitido = semanaEmitido;
	}

	public String getJustificado() {
		return this.justificado;
	}

	public void setJustificado(String justificado) {
		this.justificado = justificado;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public BigDecimal getAnio() {
		return this.anio;
	}

	public void setAnio(BigDecimal anio) {
		this.anio = anio;
	}

	public BigDecimal getMes() {
		return this.mes;
	}

	public void setMes(BigDecimal mes) {
		this.mes = mes;
	}

}
