package ec.com.rgt.sair.hbm;

// Generated 14/11/2016 03:24:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairBriEstados generated by hbmjava
 */
public class SairBriEstados implements java.io.Serializable {

	private BigDecimal idEstado;
	private String nombre,descripcion;
	private String estado;
	private Set sairBriProgramacions = new HashSet(0);

	public SairBriEstados() {
	}

	public SairBriEstados(BigDecimal idEstado) {
		this.idEstado = idEstado;
	}

	public SairBriEstados(BigDecimal idEstado, String nombre, String estado,String descripcion,
			Set sairBriProgramacions) {
		this.idEstado = idEstado;
		this.nombre = nombre;
		this.estado = estado;
		this.descripcion = descripcion;
		this.sairBriProgramacions = sairBriProgramacions;
	}

	public BigDecimal getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(BigDecimal idEstado) {
		this.idEstado = idEstado;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairBriProgramacions() {
		return this.sairBriProgramacions;
	}

	public void setSairBriProgramacions(Set sairBriProgramacions) {
		this.sairBriProgramacions = sairBriProgramacions;
	}

}
