package ec.com.rgt.sair.hbm;

// Generated 26-ene-2015 15:54:15 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairPoliticaProcedimiento generated by hbmjava
 */
public class SairPoliticaProcedimiento implements java.io.Serializable {

	private BigDecimal idProceso;
	private SairPoliticaSubProceso sairPoliticaSubProceso;
	private SairPoliticaProceso sairPoliticaProceso;
	private String nombre;
	private String estado;
	private String descripcion;
	private String objetivo;
	private String rojo;
	private String presentaRep;
	private String desProceso;
	private Set sairRutinaProcesos = new HashSet(0);
	private Set sairParRutinas = new HashSet(0);
	private Set sairParProcedimientoAmxes = new HashSet(0);
	private Set sairAmxDocumentos = new HashSet(0);

	public SairPoliticaProcedimiento() {
	}

	public SairPoliticaProcedimiento(BigDecimal idProceso) {
		this.idProceso = idProceso;
	}

	public SairPoliticaProcedimiento(BigDecimal idProceso,
			SairPoliticaSubProceso sairPoliticaSubProceso,
			SairPoliticaProceso sairPoliticaProceso, String nombre,
			String estado, String descripcion, String objetivo, String rojo,
			String presentaRep, String desProceso, Set sairRutinaProcesos, Set sairParRutinas,
			Set sairParProcedimientoAmxes, Set sairAmxDocumentos) {
		this.idProceso = idProceso;
		this.sairPoliticaSubProceso = sairPoliticaSubProceso;
		this.sairPoliticaProceso = sairPoliticaProceso;
		this.nombre = nombre;
		this.estado = estado;
		this.descripcion = descripcion;
		this.objetivo = objetivo;
		this.rojo = rojo;
		this.presentaRep = presentaRep;
		this.desProceso = desProceso;
		this.sairRutinaProcesos = sairRutinaProcesos;
		this.sairParRutinas = sairParRutinas;
		this.sairParProcedimientoAmxes = sairParProcedimientoAmxes;
		this.sairAmxDocumentos = sairAmxDocumentos;
	}

	public BigDecimal getIdProceso() {
		return this.idProceso;
	}

	public void setIdProceso(BigDecimal idProceso) {
		this.idProceso = idProceso;
	}

	public String getDesProceso() {
		return desProceso;
	}

	public void setDesProceso(String desProceso) {
		this.desProceso = desProceso;
	}

	public SairPoliticaSubProceso getSairPoliticaSubProceso() {
		return this.sairPoliticaSubProceso;
	}

	public void setSairPoliticaSubProceso(
			SairPoliticaSubProceso sairPoliticaSubProceso) {
		this.sairPoliticaSubProceso = sairPoliticaSubProceso;
	}

	public SairPoliticaProceso getSairPoliticaProceso() {
		return this.sairPoliticaProceso;
	}

	public void setSairPoliticaProceso(SairPoliticaProceso sairPoliticaProceso) {
		this.sairPoliticaProceso = sairPoliticaProceso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	public String getRojo() {
		return this.rojo;
	}

	public void setRojo(String rojo) {
		this.rojo = rojo;
	}

	public String getPresentaRep() {
		return this.presentaRep;
	}

	public void setPresentaRep(String presentaRep) {
		this.presentaRep = presentaRep;
	}

	public Set getSairRutinaProcesos() {
		return this.sairRutinaProcesos;
	}

	public void setSairRutinaProcesos(Set sairRutinaProcesos) {
		this.sairRutinaProcesos = sairRutinaProcesos;
	}

	public Set getSairParRutinas() {
		return this.sairParRutinas;
	}

	public void setSairParRutinas(Set sairParRutinas) {
		this.sairParRutinas = sairParRutinas;
	}

	public Set getSairParProcedimientoAmxes() {
		return this.sairParProcedimientoAmxes;
	}

	public void setSairParProcedimientoAmxes(Set sairParProcedimientoAmxes) {
		this.sairParProcedimientoAmxes = sairParProcedimientoAmxes;
	}

	public Set getSairAmxDocumentos() {
		return this.sairAmxDocumentos;
	}

	public void setSairAmxDocumentos(Set sairAmxDocumentos) {
		this.sairAmxDocumentos = sairAmxDocumentos;
	}

}
