package ec.com.rgt.sair.hbm;

// Generated 14-oct-2013 14:03:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairObsAccionAdm generated by hbmjava
 */
public class SairObsAccionAdm implements java.io.Serializable {

	private BigDecimal idAccionAdm;
	private String descripcion;
	private String codigo;
	private String estado;

	public SairObsAccionAdm() {
	}

	public SairObsAccionAdm(BigDecimal idAccionAdm, String descripcion) {
		this.idAccionAdm = idAccionAdm;
		this.descripcion = descripcion;
	}

	public SairObsAccionAdm(BigDecimal idAccionAdm, String descripcion,
			String codigo, String estado) {
		this.idAccionAdm = idAccionAdm;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.estado=estado;
	}

	public BigDecimal getIdAccionAdm() {
		return this.idAccionAdm;
	}

	public void setIdAccionAdm(BigDecimal idAccionAdm) {
		this.idAccionAdm = idAccionAdm;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
