package ec.com.rgt.sair.hbm;

// Generated 11-abr-2014 14:30:05 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SairRecDiscusion generated by hbmjava
 */
public class SairRecDiscusion implements java.io.Serializable {

	private BigDecimal idDiscusion;
	private SairRecRecomendacion sairRecRecomendacion;
	private String idUsuario,idUsuarioDir;
	private Date fechaIngreso;
	private String estado;
	private String discusion;
	private String url;
	private String extencion,leido;

	public SairRecDiscusion() {
	}

	public SairRecDiscusion(BigDecimal idDiscusion,
			SairRecRecomendacion sairRecRecomendacion) {
		this.idDiscusion = idDiscusion;
		this.sairRecRecomendacion = sairRecRecomendacion;
	}

	public SairRecDiscusion(BigDecimal idDiscusion,
			SairRecRecomendacion sairRecRecomendacion, String idUsuario,
			String idUsuarioDir, Date fechaIngreso, String estado,
			String discusion, String url, String extencion, String leido) {
		super();
		this.idDiscusion = idDiscusion;
		this.sairRecRecomendacion = sairRecRecomendacion;
		this.idUsuario = idUsuario;
		this.idUsuarioDir = idUsuarioDir;
		this.fechaIngreso = fechaIngreso;
		this.estado = estado;
		this.discusion = discusion;
		this.url = url;
		this.extencion = extencion;
		this.leido = leido;
	}
	
	public String getIdUsuarioDir() {
		return idUsuarioDir;
	}

	public void setIdUsuarioDir(String idUsuarioDir) {
		this.idUsuarioDir = idUsuarioDir;
	}

	public String getLeido() {
		return leido;
	}

	public void setLeido(String leido) {
		this.leido = leido;
	}

	public BigDecimal getIdDiscusion() {
		return this.idDiscusion;
	}

	public void setIdDiscusion(BigDecimal idDiscusion) {
		this.idDiscusion = idDiscusion;
	}

	public SairRecRecomendacion getSairRecRecomendacion() {
		return this.sairRecRecomendacion;
	}

	public void setSairRecRecomendacion(
			SairRecRecomendacion sairRecRecomendacion) {
		this.sairRecRecomendacion = sairRecRecomendacion;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getDiscusion() {
		return this.discusion;
	}

	public void setDiscusion(String discusion) {
		this.discusion = discusion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getExtencion() {
		return this.extencion;
	}

	public void setExtencion(String extencion) {
		this.extencion = extencion;
	}

}
