package ec.com.rgt.sair.hbm;

// Generated 23-jul-2014 9:56:17 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SairParPeriodicidad generated by hbmjava
 */
public class SairParPeriodicidad implements java.io.Serializable {

	private BigDecimal idPeriodicidad;
	private String nombre;
	private String estado;
	private Set sairParRutinas = new HashSet(0);

	public SairParPeriodicidad() {
	}

	public SairParPeriodicidad(BigDecimal idPeriodicidad) {
		this.idPeriodicidad = idPeriodicidad;
	}

	public SairParPeriodicidad(BigDecimal idPeriodicidad, String nombre,
			String estado, Set sairParRutinas) {
		this.idPeriodicidad = idPeriodicidad;
		this.nombre = nombre;
		this.estado = estado;
		this.sairParRutinas = sairParRutinas;
	}

	public BigDecimal getIdPeriodicidad() {
		return this.idPeriodicidad;
	}

	public void setIdPeriodicidad(BigDecimal idPeriodicidad) {
		this.idPeriodicidad = idPeriodicidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSairParRutinas() {
		return this.sairParRutinas;
	}

	public void setSairParRutinas(Set sairParRutinas) {
		this.sairParRutinas = sairParRutinas;
	}

}
