package ec.com.rgt.sair.hbm;

// Generated 15/10/2013 09:15:49 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import ec.com.rgt.sair.hbm.SairArea;

/**
 * Usuarios generated by hbmjava
 */
@SuppressWarnings("serial")
public class Usuarios implements java.io.Serializable {

	private String idUsuario;
	private SairArea sairArea;
	private String clave;
	private String nombresCompletos;
	private String usuarioIngreso;
	private String usuarioModificacion;
	private Date fechaIngreso;
	private Date fechaBaja;
	private String estado;
	private String nombre;
	private String apellido;
	private String email1;
	private String email2;
	private String firma;
	private String codigo;
	private String jefeInmediato;
	private String cargo;
	private String primerIngreso;
	private Date fechaExpiracionClave;
	private BigDecimal numIntentos;

	public Usuarios() {
	}

	public Usuarios(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Usuarios(String idUsuario, SairArea sairArea, String clave, String nombresCompletos,
			String usuarioIngreso, String usuarioModificacion,
			Date fechaIngreso, Date fechaBaja, String estado, String nombre,
			String apellido, String email1, String email2, String firma,
			String codigo, String jefeInmediato, 
			String cargo, String primerIngreso, Date fechaExpiracionClave, BigDecimal numIntentos) {
		this.idUsuario = idUsuario;
		this.sairArea = sairArea;
		this.clave = clave;
		this.nombresCompletos = nombresCompletos;
		this.usuarioIngreso = usuarioIngreso;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaIngreso = fechaIngreso;
		this.fechaBaja = fechaBaja;
		this.estado = estado;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email1 = email1;
		this.email2 = email2;
		this.firma = firma;
		this.codigo = codigo;
		this.jefeInmediato = jefeInmediato;
		this.cargo = cargo;
		this.primerIngreso = primerIngreso;
		this.fechaExpiracionClave = fechaExpiracionClave;
		this.numIntentos = numIntentos;  
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	
	public SairArea getSairArea() {
		return sairArea;
	}

	public void setSairArea(SairArea sairArea) {
		this.sairArea = sairArea;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombresCompletos() {
		return this.nombresCompletos;
	}

	public void setNombresCompletos(String nombresCompletos) {
		this.nombresCompletos = nombresCompletos;
	}

	public String getUsuarioIngreso() {
		return this.usuarioIngreso;
	}

	public void setUsuarioIngreso(String usuarioIngreso) {
		this.usuarioIngreso = usuarioIngreso;
	}

	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getFechaBaja() {
		return this.fechaBaja;
	}

	public void setFechaBaja(Date fechaBaja) {
		this.fechaBaja = fechaBaja;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getFirma() {
		return firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getJefeInmediato() {
		return this.jefeInmediato;
	}

	public void setJefeInmediato(String jefeInmediato) {
		this.jefeInmediato = jefeInmediato;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getPrimerIngreso() {
		return this.primerIngreso;
	}

	public void setPrimerIngreso(String primerIngreso) {
		this.primerIngreso = primerIngreso;
	}

	public Date getFechaExpiracionClave() {
		return this.fechaExpiracionClave;
	}

	public void setFechaExpiracionClave(Date fechaExpiracionClave) {
		this.fechaExpiracionClave = fechaExpiracionClave;
	}

	public BigDecimal getNumIntentos() {
		return this.numIntentos;
	}

	public void setNumIntentos(BigDecimal numIntentos) {
		this.numIntentos = numIntentos;
	}
}

